#!/bin/bash
# i-MSCP InstantSSH plugin
# Copyright (C) 2014-2015 Laurent Declercq <l.declercq@nuxwin.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA

set -e

L10N_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/../" && pwd)

rm -fR ${L10N_DIR}/mo/*
for i in `find ${L10N_DIR}/po -name '*.po' | sed -r 's/.*\/(.*)/\1/'`; do
	echo "Compiling machine object file: ${i}"
	LOCALE=`echo ${i} | cut -d '.' -f 1`
	msgfmt --strict --no-hash -o ${L10N_DIR}/mo/${LOCALE}.mo ${L10N_DIR}/po/${i}
done
