#!/bin/bash
# i-MSCP InstantSSH plugin
# Copyright (C) 2014-2015 Laurent Declercq <l.declercq@nuxwin.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA

set -e

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/../../" && pwd)
cd ${ROOT_DIR};

# Create/Update portable object template file
find . -type f -name '*.php' -print > trfiles.lst
find . -type f -name '*.tpl' -print >> trfiles.lst
/usr/bin/xgettext --copyright-holder='Laurent Declercq - All rights reserved' --package-name='InstantSSH' \
--package-version="3.2.x" --msgid-bugs-address='l.declercq@nuxwin.com' --language=PHP --keyword='tr' \
--keyword='ntr:1,2' --from-code=utf-8 --files-from=trfiles.lst --sort-output --output=./l10n/InstantSSH.pot
rm -f trfiles.lst
