<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['navtitle'] = 'Задачи';
$labels['lists'] = 'Списъци със задачи';
$labels['list'] = 'Списък със задачи';
$labels['tags'] = 'Етикети';
$labels['tasklistsubscribe'] = 'Постоянен списък';
$labels['listsearchresults'] = 'Налични списъци';
$labels['findlists'] = 'Намери списъци със задачи ...';
$labels['notasklistsfound'] = 'Не бяха открити списъци със задачи ...';
$labels['nrtasklistsfound'] = 'Бяха намерени $nr списъка';
$labels['removelist'] = 'Премахване от списъка';
$labels['showcaldavurl'] = 'Покажи CalDAV URL адрес';
$labels['caldavurldescription'] = 'Копирайте <a href="http://en.wikipedia.org/wiki/CalDAV" target="_blank">CalDAV</a> URL адреса в клиентско приложение (например Evolution или Mozilla Thunderbird), за да синхронизирате този списък със задачи на вашият компютър или мобилно устройство.';
$labels['newtask'] = 'Нова Задача';
$labels['createtask'] = 'Създаване на задача <Enter>';
$labels['createnewtask'] = 'Създаване на нова Задача (напр. Понеделник, На работа)';
$labels['createfrommail'] = 'Запази като задача';
$labels['printtitle'] = 'Принтиране на задачи';
$labels['newtask'] = 'Нова Задача';
