<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['navtitle'] = 'Задачи';
$labels['printdescriptions'] = 'Печат на описанията';
$labels['edit'] = 'Промяна';
$labels['description'] = 'Описание';
$labels['start'] = 'Начало';
$labels['alarms'] = 'Напомняне';
$labels['status'] = 'Статус';
$labels['today'] = 'Днес';
$labels['tomorrow'] = 'Утре';
$labels['removetag'] = 'Изтриване';
$labels['save'] = 'Запис';
$labels['cancel'] = 'Отказ';
$labels['tabsummary'] = 'Заглавие';
$labels['tabattachments'] = 'Прикрепени файлове';
$labels['tabsharing'] = 'Споделяне';
$labels['listname'] = 'Име';
$labels['savingdata'] = 'Запазване на данни...';
$labels['role'] = 'Роля';
$labels['confirmstate'] = 'Статус';
$labels['roleorganizer'] = 'Организатор';
$labels['rolerequired'] = 'Задължителен';
$labels['roleoptional'] = 'По избор';
$labels['sendinvitations'] = 'Изпращане на покани';
$labels['andnmore'] = '$nr повече...';
