<?php

$labels = array();
$labels['navtitle'] = 'Úkoly';
$labels['lists'] = 'Seznamy úkolů';
$labels['list'] = 'Seznam úkolů';
$labels['tags'] = 'Štítky';

$labels['newtask'] = 'Nový úkol';
$labels['createnewtask'] = 'Vytvořit nový úkol (např. sobota, posekat trávník)';
$labels['createfrommail'] = 'Uložit úkol';
$labels['mark'] = 'Označit';
$labels['unmark'] = 'Odznačit';
$labels['edit'] = 'Upravit';
$labels['delete'] = 'Smazat';
$labels['title'] = 'Titulek';
$labels['description'] = 'Popis';
$labels['datetime'] = 'Konec';
$labels['start'] = 'Začátek';
$labels['alarms'] = 'Připomenutí';

$labels['all'] = 'Všechny';
$labels['flagged'] = 'Označkované';
$labels['complete'] = 'Dokončené';
$labels['overdue'] = 'Zpožděné';
$labels['today'] = 'Dnes';
$labels['tomorrow'] = 'Zítra';
$labels['next7days'] = 'Příštích 7 dnů';
$labels['later'] = 'Později';
$labels['nodate'] = 'Žádné datum';
$labels['removetag'] = 'Odstranit';

$labels['taskdetails'] = 'Podrobnosti';
$labels['newtask'] = 'Nový úkol';
$labels['edittask'] = 'Upravit úkol';
$labels['save'] = 'Uložit';
$labels['cancel'] = 'Storno';
$labels['addsubtask'] = 'Přidat podúkol';
$labels['deletetask'] = 'Smazat úkol';
$labels['deletethisonly'] = 'Smazat pouze tento úkol';
$labels['deletewithchilds'] = 'Smazat se všemi podúkoly';

$labels['tabsummary'] = 'Souhrn';
$labels['tabrecurrence'] = 'Opakování';
$labels['tabattachments'] = 'Přílohy';
$labels['tabsharing'] = 'Sdílení';

$labels['editlist'] = 'Upravit seznam';
$labels['createlist'] = 'Přidat seznam';
$labels['listactions'] = 'Možnosti seznamu...';
$labels['listname'] = 'Název';
$labels['showalarms'] = 'Ukázat upozornění';
$labels['import'] = 'Import';

// date words
$labels['on'] = ' ';
$labels['at'] = ' ';
$labels['this'] = 'tento';
$labels['next'] = 'příští';

// messages
$labels['savingdata'] = 'Ukládám data...';
$labels['errorsaving'] = 'Nelze uložit data.';
$labels['notasksfound'] = 'Nebyly nalezeny žádné úkoly vyhovující daným kritériím';
$labels['invalidstartduedates'] = 'Počáteční datum nesmí být pozdější než koncové datum.';
$labels['deletetasktconfirm'] = 'Opravdu chcete smazat tento úkol?';
$labels['deleteparenttasktconfirm'] = 'Opravdu chcete smazat tento úkol a všechny jeho podúkoly?';
$labels['deletelistconfirm'] = 'Opravdu chcete smazat tento seznam včetně všech úkolů?';
