<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['navtitle'] = 'Tareas';
$labels['edit'] = 'Editar';
$labels['delete'] = 'Borrar';
$labels['title'] = 'Título';
$labels['description'] = 'Descripción';
$labels['taskdetails'] = 'Detalles';
$labels['save'] = 'Guardar';
$labels['cancel'] = 'Cancelar';
$labels['listname'] = 'Nombre';
$labels['savingdata'] = 'Guardando datos...';
$labels['role'] = 'Rol';
$labels['rolerequired'] = 'Requerido';
$labels['roleoptional'] = 'Opcional';
$labels['comment'] = 'Comentario';
