<?php

$labels = array();
$labels['navtitle'] = 'Tâches';
$labels['lists'] = 'Liste des tâches';
$labels['list'] = 'Liste de tâche';
$labels['tags'] = 'Étiquettes';

$labels['newtask'] = 'Nouvelle tâche';
$labels['createnewtask'] = 'Créer une nouvelle tâche (ex : Samedi, tondre la pelouse)';
$labels['createfrommail'] = 'Enregistrer la tâche';
$labels['mark'] = 'Sélectionner';
$labels['unmark'] = 'Désélectionner';
$labels['edit'] = 'Modifier';
$labels['delete'] = 'Supprimet';
$labels['title'] = 'Titre';
$labels['description'] = 'Description';
$labels['datetime'] = 'Date/heure';
$labels['start'] = 'Début';
$labels['alarms'] = 'Rappel';

$labels['all'] = 'Tous';
$labels['flagged'] = 'Marqué';
$labels['complete'] = 'Terminé';
$labels['overdue'] = 'En retard';
$labels['today'] = 'Aujourd\'hui';
$labels['tomorrow'] = 'Demain';
$labels['next7days'] = '7 prochains jours';
$labels['later'] = 'Plus tard';
$labels['nodate'] = 'Pas de date';
$labels['removetag'] = 'Supprimer';

$labels['taskdetails'] = 'Détails';
$labels['newtask'] = 'Nouvelle tâche';
$labels['edittask'] = 'Modifier la tâche';
$labels['save'] = 'Enregistrer';
$labels['cancel'] = 'Annuler';
$labels['addsubtask'] = 'Ajouter une sous-tâche';
$labels['deletetask'] = 'Supprimer la tâche';
$labels['deletethisonly'] = 'Supprimer seulement cette tâche';
$labels['deletewithchilds'] = 'Supprimer avec toutes les sous-tâches';

$labels['tabsummary'] = 'Résumé';
$labels['tabrecurrence'] = 'Récurrence';
$labels['tabattachments'] = 'Pièces jointes';
$labels['tabsharing'] = 'Partage';

$labels['editlist'] = 'Modifier une liste';
$labels['createlist'] = 'Ajouter une liste';
$labels['listactions'] = 'Liste des options';
$labels['listname'] = 'Nom';
$labels['showalarms'] = 'Montrer les alarmes';
$labels['import'] = 'Importer';

// date words
$labels['on'] = 'sur';
$labels['at'] = 'à';
$labels['this'] = 'ce';
$labels['next'] = 'suivant';

// mesages
$labels['savingdata'] = 'Enregistrer...';
$labels['errorsaving'] = 'Échec de l\'enregistrement';
$labels['notasksfound'] = 'Pas de tâche trouvé avec les critères sélectionnés';
$labels['invalidstartduedates'] = 'La date de début ne doit pas être supérieur à la date de fin';
$labels['deletetasktconfirm'] = 'Êtes-vous sur de vouloir supprimer cette tâche?';
$labels['deleteparenttasktconfirm'] = 'Êtes-vous sur de vouloir supprimer cette tâche et ses sous-tâches?';
$labels['deletelistconfirm'] = 'Êtes-vous sur de vouloir supprimer cette liste et toutes ses tâches?';
