<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['export'] = 'Export';
$labels['exporttitle'] = 'Export to iCalendar';
$labels['exportattachments'] = 'With attachments';
$labels['tasklistsubscribe'] = 'List permanently';
$labels['searchterms'] = 'Search terms';
$labels['removelist'] = 'Remove from list';
$labels['printdescriptions'] = 'Print descriptions';
$labels['edit'] = 'Edit';
$labels['description'] = 'Description';
$labels['start'] = 'Start';
$labels['starttime'] = 'Start time';
$labels['alarms'] = 'Reminder';
$labels['repeat'] = 'Repeat';
$labels['status'] = 'Status';
$labels['status-cancelled'] = 'Cancelled';
$labels['created'] = 'Created';
$labels['changed'] = 'Last Modified';
$labels['taskoptions'] = 'Options';
$labels['all'] = 'All';
$labels['today'] = 'Today';
$labels['tomorrow'] = 'Tomorrow';
$labels['taskdetails'] = 'Details';
$labels['save'] = 'Save';
$labels['cancel'] = 'Cancel';
$labels['tabsummary'] = 'Summary';
$labels['tabrecurrence'] = 'Recurrence';
$labels['tabattachments'] = 'Attachments';
$labels['tabsharing'] = 'Sharing';
$labels['listname'] = 'Name';
$labels['showalarms'] = 'Show reminders';
$labels['savingdata'] = 'Saving data...';
$labels['role'] = 'Role';
$labels['availability'] = 'Avail.';
$labels['confirmstate'] = 'Status';
$labels['roleorganizer'] = 'Organizer';
$labels['rolerequired'] = 'Required';
$labels['roleoptional'] = 'Optional';
$labels['rolechair'] = 'Chair';
$labels['sendinvitations'] = 'Send invitations';
$labels['itipupdatesubject'] = '"$title" has been updated';
$labels['taskhistory'] = 'History';
$labels['objectchangelog'] = 'Change History';
$labels['objectdiffnotavailable'] = 'No comparison possible for the selected revisions';
$labels['itipcomment'] = 'Invitation/notification comment';
$labels['andnmore'] = '$nr more...';
$labels['delegatedto'] = 'Delegated to: ';
$labels['delegatedfrom'] = 'Delegated from: ';
$labels['comment'] = 'Comment';
$labels['attendeupdateesuccess'] = 'Successfully updated the participant\'s status';
$labels['itipinvalidrequest'] = 'This invitation is no longer valid';
