<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['navtitle'] = 'Feladatok';
$labels['lists'] = 'Feladatlisták';
$labels['list'] = 'Feladatlista';
$labels['tags'] = 'Kulcsszavak';
$labels['newtask'] = 'Új feladat';
$labels['createnewtask'] = 'Új feladat címe';
$labels['createfrommail'] = 'Mentés feladatként';
$labels['printdescriptions'] = 'Leírás nyomtatása';
$labels['mark'] = 'Jelölés be';
$labels['unmark'] = 'Jelölés ki';
$labels['edit'] = 'Módosítás';
$labels['delete'] = 'Törlés';
$labels['title'] = 'Tárgy';
$labels['description'] = 'Leírás';
$labels['datetime'] = 'Határidő';
$labels['start'] = 'Kezdet';
$labels['alarms'] = 'Emlékeztető';
$labels['repeat'] = 'Ismétlődik';
$labels['status'] = 'Stát.';
$labels['all'] = 'Minden feladat';
$labels['flagged'] = 'Jelölt';
$labels['complete'] = 'Teljesített';
$labels['overdue'] = 'Túllépett';
$labels['today'] = 'Mai napi';
$labels['tomorrow'] = 'Holnapi';
$labels['next7days'] = 'Következő 7 napi';
$labels['later'] = 'Későbbi';
$labels['nodate'] = 'Dátum nélküli';
$labels['removetag'] = 'Eltávolítás';
$labels['taskdetails'] = 'Részletek';
$labels['newtask'] = 'Új feladat';
$labels['edittask'] = 'Módosítás';
$labels['save'] = 'Mentés';
$labels['cancel'] = 'Mégse';
$labels['addsubtask'] = 'Új részfeladat';
$labels['deletetask'] = 'Törlés';
$labels['deletethisonly'] = 'Csak ezen feladat törlése';
$labels['deletewithchilds'] = 'Törlés részfeladatokkal együtt';
$labels['tabsummary'] = 'Tárgy';
$labels['tabrecurrence'] = 'Ismétlődés';
$labels['tabattachments'] = 'Mellékletek';
$labels['tabsharing'] = 'Megosztás';
$labels['editlist'] = 'Lista szerkesztése';
$labels['createlist'] = 'Lista hozzáadása';
$labels['listactions'] = 'Lista beállítások...';
$labels['listname'] = 'Név';
$labels['showalarms'] = 'Emlékeztetők megjelenítése';
$labels['import'] = 'Importálás';
$labels['focusview'] = 'Csak ezen lista megjelenítése';
$labels['on'] = 'dátum';
$labels['at'] = 'időpont';
$labels['this'] = 'ezen';
$labels['next'] = 'következő';
$labels['savingdata'] = 'Adatok mentése...';
$labels['errorsaving'] = 'Az adatok mentése nem sikerült';
$labels['notasksfound'] = 'A megadott kritériumoknak nem felelt meg egy feladat sem';
$labels['invalidstartduedates'] = 'A kezdeti idő nem lehet később, mint a határidő';
$labels['deletetasktconfirm'] = 'Biztos benne, hogy törölni szeretné ezt a feladatot?';
$labels['deleteparenttasktconfirm'] = 'DBiztos benne, hogy törölni szeretné ezt a feladatot, az összes részfeladattal együtt?';
$labels['deletelistconfirm'] = 'Biztos benne, hogy törölni szeretné ezt a listát, az összes benne lévő feladattal együtt?';
$labels['deletelistconfirmrecursive'] = 'Biztos benne, hogy törölni szeretné ezt a listát, az összes benne lévő listával és feladattal együtt?';
$labels['role'] = 'Szerepkör';
$labels['availability'] = 'Elérh.';
$labels['confirmstate'] = 'Stát.';
$labels['roleorganizer'] = 'Szervező';
$labels['rolerequired'] = 'Kötelező';
$labels['roleoptional'] = 'Opcionális';
$labels['rolechair'] = 'Elnöklő';
$labels['sendinvitations'] = 'Meghívók küldése';
$labels['itipupdatesubject'] = '$title - módosítva';
$labels['itipcancelsubject'] = '$title - lemondva';
$labels['andnmore'] = 'még $nr ...';
$labels['delegatedto'] = 'Beosztva ide: ';
$labels['delegatedfrom'] = 'Beosztva innen: ';
