<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['navtitle'] = 'タスク';
$labels['lists'] = 'タスク一覧';
$labels['list'] = 'タスク一覧';
$labels['tags'] = 'タグ';
$labels['newtask'] = '新しいタスク';
$labels['createnewtask'] = '新しいタスクの生成(例:土曜日、芝生を刈る)';
$labels['createfrommail'] = 'タスクとして保存';
$labels['printdescriptions'] = '説明印刷';
$labels['mark'] = 'マーク';
$labels['unmark'] = 'マーク解除';
$labels['edit'] = '編集';
$labels['delete'] = '削除';
$labels['title'] = 'タイトル';
$labels['description'] = '説明';
$labels['start'] = '開始';
$labels['alarms'] = '通知';
$labels['repeat'] = '繰返し';
$labels['status'] = '状態';
$labels['all'] = '全て';
$labels['flagged'] = 'フラグ';
$labels['complete'] = '完了';
$labels['overdue'] = '期限切れ';
$labels['today'] = '今日';
$labels['tomorrow'] = '明日';
$labels['next7days'] = '翌 7 日';
$labels['later'] = '後で';
$labels['nodate'] = '期日なし';
$labels['removetag'] = '削除';
$labels['taskdetails'] = '詳細';
$labels['newtask'] = '新しいタスク';
$labels['edittask'] = 'タスク編集';
$labels['save'] = '保存';
$labels['cancel'] = 'キャンセル';
$labels['addsubtask'] = 'サブタスク追加';
$labels['deletetask'] = 'タスク削除';
$labels['deletethisonly'] = 'このタスクのみ削除';
$labels['deletewithchilds'] = '全てのサブタスクも削除';
$labels['tabsummary'] = '要約';
$labels['tabrecurrence'] = '繰返し';
$labels['tabattachments'] = '添付';
$labels['tabsharing'] = '共有';
$labels['editlist'] = '一覧編集';
$labels['createlist'] = '一覧追加';
$labels['listactions'] = '一覧オプション';
$labels['listname'] = '名前';
$labels['import'] = 'インポート';
$labels['on'] = '上';
$labels['at'] = 'の';
$labels['this'] = 'この';
$labels['next'] = '次';
$labels['savingdata'] = 'データを保存中…';
$labels['errorsaving'] = 'データが保存できませんでした。';
$labels['notasksfound'] = '条件に該当するタスクは見つかりません';
$labels['invalidstartduedates'] = '開始日は終了日の前でなければいけません。';
$labels['deletetasktconfirm'] = 'このタスクを本当に削除しますか?';
$labels['deleteparenttasktconfirm'] = 'このタスクとすべてのサブタスクを本当に削除しますか?';
$labels['deletelistconfirm'] = '本当に、この一覧とすべてのタスクを一緒に削除しますか?';
$labels['role'] = 'ロール';
$labels['availability'] = '利用可';
$labels['confirmstate'] = '状態';
$labels['roleorganizer'] = '編成者';
$labels['rolerequired'] = '要件';
$labels['roleoptional'] = 'オプション';
$labels['sendinvitations'] = '招待を送る';
$labels['itipupdatesubject'] = '"$title" はアップデートされました';
$labels['itipcancelsubject'] = '"$title" は変更されました';
$labels['andnmore'] = '$nr さらに…';
$labels['attendeupdateesuccess'] = '出席者状況を更新しました';
$labels['itipinvalidrequest'] = 'この招待は間もなく無効になります';
