<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['export'] = '내보내기';
$labels['exporttitle'] = 'iCalendar로 내보내기';
$labels['exportattachments'] = '첨부됨';
$labels['removelist'] = '목록에서 삭제';
$labels['printdescriptions'] = '내용 출력';
$labels['edit'] = '수정';
$labels['description'] = '설명';
$labels['start'] = '시작';
$labels['starttime'] = '시작 시간';
$labels['alarms'] = '알림';
$labels['repeat'] = '반복';
$labels['links'] = '참조';
$labels['status'] = '상태';
$labels['status-cancelled'] = '취소됨';
$labels['created'] = '작성됨';
$labels['changed'] = '마지막으로 수정됨';
$labels['taskoptions'] = '옵션';
$labels['all'] = '전체';
$labels['today'] = '오늘';
$labels['tomorrow'] = '내일';
$labels['save'] = '저장';
$labels['cancel'] = '취소';
$labels['tabsummary'] = '요약';
$labels['tabrecurrence'] = '반복';
$labels['listname'] = '이름';
$labels['showalarms'] = '알림 보이기';
$labels['savingdata'] = '자료 저장중...';
$labels['availability'] = '가능';
$labels['confirmstate'] = '상태';
$labels['roleorganizer'] = '주최자';
$labels['rolerequired'] = '필수';
$labels['roleoptional'] = '선택';
$labels['rolechair'] = '좌석';
$labels['sendinvitations'] = '초대장 보내기';
$labels['taskhistory'] = '이력';
$labels['objectrestoreerror'] = '이전 버전으로 복구하지 못하였습니다';
$labels['andnmore'] = '$nr 더...';
$labels['delegatedto'] = '위임 :';
$labels['delegatedfrom'] = '위임받음 :';
$labels['comment'] = '코멘트';
$labels['itipinvalidrequest'] = '이 초대장은 더이상 유효하지 않습니다';
