<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['navtitle'] = 'Taken';
$labels['lists'] = 'Takenlijsten';
$labels['list'] = 'Takenlijst';
$labels['tags'] = 'Labels';
$labels['tasklistsubscribe'] = 'Permanent weergeven';
$labels['newtask'] = 'Nieuwe Taak';
$labels['createnewtask'] = 'Creer een nieuwe Taak (bijv. Zaterdag, gras maaien)';
$labels['createfrommail'] = 'Als taak opslaan';
$labels['printtitle'] = 'Taken afdrukken';
$labels['printdescriptions'] = 'Print beschrijvingen';
$labels['mark'] = 'Markeren';
$labels['unmark'] = 'Demarkeren';
$labels['edit'] = 'Wijzigen';
$labels['delete'] = 'Verwijderen';
$labels['title'] = 'Titel';
$labels['description'] = 'Beschrijving';
$labels['datetime'] = 'Vóór';
$labels['start'] = 'Begin';
$labels['alarms'] = 'Herinnering';
$labels['repeat'] = 'Herhaal';
$labels['all'] = 'Alle';
$labels['flagged'] = 'Gemarkeerd';
$labels['complete'] = 'Compleet';
$labels['completeness'] = 'Progress';
$labels['overdue'] = 'Achterstallig';
$labels['today'] = 'Vandaag';
$labels['tomorrow'] = 'Morgen';
$labels['next7days'] = 'Volgende 7 dagen';
$labels['nodate'] = 'geen datum';
$labels['removetag'] = 'Verwijder';
$labels['newtask'] = 'Nieuwe Taak';
$labels['edittask'] = 'Taak Wijzigen';
$labels['save'] = 'Opslaan';
$labels['cancel'] = 'Annuleren';
$labels['addsubtask'] = 'Voeg subtaak toe';
$labels['deletetask'] = 'Verwijder taak';
$labels['deletethisonly'] = 'Verwijder alleen deze taak';
$labels['deletewithchilds'] = 'Verwijder inclusief subtaken';
$labels['tabsummary'] = 'Samenvatting';
$labels['tabrecurrence'] = 'Herhaling';
$labels['tabassignments'] = 'Assignments';
$labels['tabattachments'] = 'Toebehoren';
$labels['tabsharing'] = 'Delen';
$labels['editlist'] = 'Lijst wijzigen';
$labels['createlist'] = 'Lijst toevoegen';
$labels['listactions'] = 'Lijst opties...';
$labels['listname'] = 'Naam';
$labels['showalarms'] = 'Laat herinneringen zien';
$labels['import'] = 'Importeren';
$labels['viewactions'] = 'View actions';
$labels['focusview'] = 'Bekijk alleen deze lijst';
$labels['on'] = 'op';
$labels['at'] = 'om';
$labels['this'] = 'deze';
$labels['next'] = 'volgende';
$labels['savingdata'] = 'Data wordt opgeslagen...';
$labels['errorsaving'] = 'Fout in opslaan van data.';
$labels['notasksfound'] = 'Geen taken gevonden voor de gegeven criteria';
$labels['invalidstartduedates'] = 'Begin datum kan niet later zijn dan vervaldag.';
$labels['deletetasktconfirm'] = 'Wilt u deze taak echt verwijderen?';
$labels['deleteparenttasktconfirm'] = 'Wilt u deze taak en alle subtaken echt verwijderen?';
$labels['deletelistconfirm'] = 'Wilt u deze lijst met alle taken echt verwijderen?';
$labels['deletelistconfirmrecursive'] = 'Wilt u deze lijst en alle taken en subtaken echt verwijderen?';
$labels['role'] = 'Rol';
$labels['availability'] = 'Beschikb.';
$labels['roleorganizer'] = 'Organisatie';
$labels['rolerequired'] = 'Verplicht';
$labels['roleoptional'] = 'Optioneel';
$labels['rolechair'] = 'Voorzitter';
$labels['sendinvitations'] = 'Verzend uitnodigingen';
$labels['itipupdatesubject'] = '"$title" is gewijzigd';
$labels['itipcancelsubject'] = '"$title" is geannuleerd';
$labels['andnmore'] = '$nr meer...';
$labels['delegatedto'] = 'Gedelegeerd aan';
$labels['delegatedfrom'] = 'Gedelegeerd door';
$labels['comment'] = 'Opmerking';
