<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['navtitle'] = 'Zadania';
$labels['lists'] = 'Lista zadań';
$labels['list'] = 'Lista zadań';
$labels['tags'] = 'Tagi';
$labels['listsearchresults'] = 'Dostępne listy zadań';
$labels['findlists'] = 'Szukaj list zadań...';
$labels['notasklistsfound'] = 'Nie znaleziono list zadań';
$labels['removelist'] = 'Usuń z listy';
$labels['newtask'] = 'Nowe zadanie';
$labels['createtask'] = 'Utwórz zadanie <Enter>';
$labels['createnewtask'] = 'Utwórz nowe zadanie (np sobota, zrobić zakupy)';
$labels['createfrommail'] = 'Zapisz jako zadanie';
$labels['edit'] = 'Edytuj';
$labels['delete'] = 'Usuń';
$labels['title'] = 'Tytuł';
$labels['description'] = 'Opis';
$labels['start'] = 'Start';
$labels['repeat'] = 'Powtórz';
$labels['status-cancelled'] = 'Anulowane';
$labels['created'] = 'Utworzone';
$labels['changed'] = 'Ostatnia modyfikacja';
$labels['all'] = 'Wszystko';
$labels['today'] = 'Dzisiaj';
$labels['tomorrow'] = 'Jutro';
$labels['next7days'] = 'Następne 7 dni';
$labels['later'] = 'Później';
$labels['assigned'] = 'Przydzielone';
$labels['mytasks'] = 'Moje zadania';
$labels['mytaskstitle'] = 'Zadania przypisane do Ciebie';
$labels['nodate'] = 'brak daty';
$labels['removetag'] = 'Usuń';
$labels['auto'] = 'Auto';
$labels['taskdetails'] = 'Szczegóły';
$labels['newtask'] = 'Nowe zadanie';
$labels['edittask'] = 'Edytuj zadanie';
$labels['save'] = 'Zapisz';
$labels['cancel'] = 'Anuluj';
$labels['addsubtask'] = 'Dodaj podzadanie';
$labels['deletetask'] = 'Usuń zadanie';
$labels['deletethisonly'] = 'Usuń tylko to zadanie';
$labels['deletewithchilds'] = 'Usuń wraz z podzadaniami';
$labels['taskactions'] = 'Opcje zadania';
$labels['tabsummary'] = 'Podsumowanie';
$labels['editlist'] = 'Edytuj listę';
$labels['createlist'] = 'Dodaj listę';
$labels['listactions'] = 'Opcje listy...';
$labels['listname'] = 'Nazwa';
$labels['import'] = 'Importuj';
$labels['rolerequired'] = 'Wymagane';
$labels['andnmore'] = '$nr więcej...';
