<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['export'] = 'Exportar';
$labels['exporttitle'] = 'Exportar para iCalendar';
$labels['exportattachments'] = 'Incluir anexos';
$labels['tasklistsubscribe'] = 'Listar permanentemente';
$labels['searchterms'] = 'Search terms';
$labels['removelist'] = 'Remove from list';
$labels['printdescriptions'] = 'Descrições de impressão';
$labels['edit'] = 'Editar';
$labels['description'] = 'Descrição';
$labels['start'] = 'Início';
$labels['starttime'] = 'Start time';
$labels['alarms'] = 'Lembrete';
$labels['repeat'] = 'Repetir';
$labels['links'] = 'Reference';
$labels['status'] = 'Situação';
$labels['status-cancelled'] = 'Cancalado';
$labels['created'] = 'Created';
$labels['changed'] = 'Last Modified';
$labels['taskoptions'] = 'Opções';
$labels['all'] = 'Todos';
$labels['today'] = 'Hoje';
$labels['tomorrow'] = 'Amanhã';
$labels['removelink'] = 'Remove email reference';
$labels['taskdetails'] = 'Detalhes';
$labels['save'] = 'Gravar';
$labels['cancel'] = 'Cancelar';
$labels['tabsummary'] = 'Sumário';
$labels['tabrecurrence'] = 'Repetição';
$labels['tabattachments'] = 'Anexos';
$labels['tabsharing'] = 'Compartilhamento';
$labels['listname'] = 'Nome';
$labels['showalarms'] = 'Show reminders';
$labels['savingdata'] = 'Salvando dados...';
$labels['role'] = 'Papel';
$labels['availability'] = 'Disp.';
$labels['confirmstate'] = 'Situação';
$labels['roleorganizer'] = 'Organizador';
$labels['rolerequired'] = 'Obrigatório';
$labels['roleoptional'] = 'Opcional';
$labels['rolechair'] = 'Chair';
$labels['sendinvitations'] = 'Enviar convites';
$labels['itipupdatesubject'] = '"$title" foi atualizado';
$labels['itipcancelsubject'] = '"$title" foi cancelado';
$labels['taskhistory'] = 'Histórico';
$labels['objectchangelog'] = 'Alterar histórico';
$labels['objectdiff'] = 'Diferenças entre $rev1 e $rev2';
$labels['objectdiffnotavailable'] = 'Não é possível comparar as revisões selecionadas';
$labels['objectrestoresuccess'] = 'A versão $rev foi reposta com sucesso.';
$labels['objectrestoreerror'] = 'Não foi possível repor a versão anterior.';
$labels['itipcomment'] = 'Invitation/notification comment';
$labels['andnmore'] = '$nr mais...';
$labels['delegatedto'] = 'Delegado para:';
$labels['delegatedfrom'] = 'Delegado de:';
$labels['comment'] = 'Comentário';
$labels['attendeupdateesuccess'] = 'O status do participante foi atualizado com sucesso.';
$labels['itipinvalidrequest'] = 'Este convite não é mais válido';
