<?php

$labels = array();
$labels['navtitle'] = 'Задачи';
$labels['lists'] = 'Списки задач';
$labels['list'] = 'Список задач';
$labels['tags'] = 'Теги';

$labels['newtask'] = 'Новая задача';
$labels['createnewtask'] = 'Создать новую задачу (пример: Суббота, покосить газон)';
$labels['createfrommail'] = 'Сохранить как задачу';
$labels['mark'] = 'Отметить';
$labels['unmark'] = 'Снять';
$labels['edit'] = 'Редактировать';
$labels['delete'] = 'Удалить';
$labels['title'] = 'Заголовок';
$labels['description'] = 'Описание';
$labels['datetime'] = 'Дата/Время';
$labels['start'] = 'Начало';
$labels['alarms'] = 'Напоминание';

$labels['all'] = 'Все';
$labels['flagged'] = 'Отмеченные';
$labels['complete'] = 'Завершенные';
$labels['overdue'] = 'Просроченные';
$labels['today'] = 'Сегодня';
$labels['tomorrow'] = 'Завтра';
$labels['next7days'] = 'Ближайшая неделя';
$labels['later'] = 'Позднее';
$labels['nodate'] = 'без даты';
$labels['removetag'] = 'Убрать';

$labels['taskdetails'] = 'Подробнее';
$labels['newtask'] = 'Новая задача';
$labels['edittask'] = 'Редактировать задачу';
$labels['save'] = 'Сохранить';
$labels['cancel'] = 'Отмена';
$labels['addsubtask'] = 'Добавить подзадачу';
$labels['deletetask'] = 'Удалить задачу';
$labels['deletethisonly'] = 'Удалить только эту задачу';
$labels['deletewithchilds'] = 'Удалить задачу и все ее подзадачи';

$labels['tabsummary'] = 'Сводка';
$labels['tabrecurrence'] = 'Повтор';
$labels['tabattachments'] = 'Вложения';
$labels['tabsharing'] = 'Поделиться';

$labels['editlist'] = 'Изменить список';
$labels['createlist'] = 'Добавить список';
$labels['listactions'] = 'Действия со списком...';
$labels['listname'] = 'Название';
$labels['showalarms'] = 'Показывать уведомления';
$labels['import'] = 'Импорт';

// date words
$labels['on'] = 'в';
$labels['at'] = 'в';
$labels['this'] = 'этот';
$labels['next'] = 'следующий';

// mesages
$labels['savingdata'] = 'Сохранение данных...';
$labels['errorsaving'] = 'Не удалось сохранить.';
$labels['notasksfound'] = 'По заданному условию не найдено задач';
$labels['invalidstartduedates'] = 'Начальная дата не может превышать конечную.';
$labels['deletetasktconfirm'] = 'Вы действительно хотите удалить эту задачу?';
$labels['deleteparenttasktconfirm'] = 'Вы действительно хотите удалить эту задачу и все ее подзадачи?';
$labels['deletelistconfirm'] = 'Вы действительно хотите удалить этот список и все его задачи?';
