<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['export'] = 'Exportovať';
$labels['exporttitle'] = 'Exportovať do iCalendar';
$labels['exportattachments'] = 'S prílohami';
$labels['removelist'] = 'Odstrániť zo zoznamu';
$labels['edit'] = 'Upraviť';
$labels['description'] = 'Popis';
$labels['start'] = 'Začiatok';
$labels['starttime'] = 'Čas začiatku';
$labels['repeat'] = 'Opakovať';
$labels['status'] = 'Stav';
$labels['status-cancelled'] = 'Zrušené';
$labels['save'] = 'Uložiť';
$labels['cancel'] = 'Zrušiť';
$labels['tabsummary'] = 'Sumár';
$labels['listname'] = 'Meno';
$labels['confirmstate'] = 'Stav';
