<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['tasklistsubscribe'] = 'Lista permanent';
$labels['searchterms'] = 'Sökord';
$labels['removelist'] = 'Ta bort från lista';
$labels['printdescriptions'] = 'Skriv ut beskrivning';
$labels['edit'] = 'Redigera';
$labels['description'] = 'Beskrivning';
$labels['start'] = 'Start';
$labels['starttime'] = 'Starttid';
$labels['alarms'] = 'Påminnelse';
$labels['repeat'] = 'Upprepa';
$labels['links'] = 'Referens';
$labels['status'] = 'Status';
$labels['status-cancelled'] = 'Inställd';
$labels['created'] = 'Skapad';
$labels['changed'] = 'Senast ändrad';
$labels['all'] = 'Alla';
$labels['today'] = 'Idag';
$labels['tomorrow'] = 'Imorgon';
$labels['removelink'] = 'Ta bort e-postreferens';
$labels['taskdetails'] = 'Detaljer';
$labels['save'] = 'Spara';
$labels['cancel'] = 'Avbryt';
$labels['tabsummary'] = 'Sammanfattning';
$labels['tabrecurrence'] = 'Återkommande';
$labels['tabattachments'] = 'Bilagor';
$labels['tabsharing'] = 'Delning';
$labels['listname'] = 'Namn';
$labels['showalarms'] = 'Visa påminnelser';
$labels['savingdata'] = 'Sparar data ...';
$labels['role'] = 'Roll';
$labels['availability'] = 'Tillg.';
$labels['confirmstate'] = 'Status';
$labels['roleorganizer'] = 'Organisatör';
$labels['rolerequired'] = 'Obligatorisk';
$labels['roleoptional'] = 'Valfritt';
$labels['rolechair'] = 'Stol';
$labels['sendinvitations'] = 'Skicka inbjudningar';
$labels['itipupdatesubject'] = '"$title" har uppdaterats';
$labels['itipcancelsubject'] = '"$title" har ställts in';
$labels['itipcomment'] = 'Kommentar till inbjudan/meddelande';
$labels['andnmore'] = '$nr fler ...';
$labels['delegatedto'] = 'Delegerad till:';
$labels['delegatedfrom'] = 'Delegerad från:';
$labels['comment'] = 'Kommentar';
$labels['attendeupdateesuccess'] = 'Uppdaterade deltagarens status';
$labels['itipinvalidrequest'] = 'Denna inbjudan är inte längre giltig';
