<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['navtitle'] = 'Задачі';
$labels['export'] = 'Експорт';
$labels['exporttitle'] = 'Експорт в iCalendar';
$labels['exportattachments'] = 'Із вкладеннями';
$labels['tasklistsubscribe'] = 'Завжди показувати';
$labels['searchterms'] = 'Умови пошуку';
$labels['removelist'] = 'Вилучити зі списку';
$labels['printdescriptions'] = 'Друк опису';
$labels['edit'] = 'Редагувати';
$labels['description'] = 'Опис';
$labels['start'] = 'Початок';
$labels['starttime'] = 'Час початку';
$labels['alarms'] = 'Нагадування';
$labels['repeat'] = 'Повторити';
$labels['status'] = 'Статус';
$labels['status-cancelled'] = 'Відмінений';
$labels['created'] = 'Створена';
$labels['changed'] = 'Змінена';
$labels['taskoptions'] = 'Опції';
$labels['all'] = 'Всі';
$labels['today'] = 'Сьогодні';
$labels['tomorrow'] = 'Завтра';
$labels['taskdetails'] = 'Подробиці';
$labels['save'] = 'Зберегти';
$labels['cancel'] = 'Відмінити';
$labels['tabsummary'] = 'Резюме';
$labels['tabrecurrence'] = 'Повторення';
$labels['tabattachments'] = 'Вкладення';
$labels['tabsharing'] = 'Спільне використання';
$labels['listname'] = 'Назва';
$labels['showalarms'] = 'Показувати нагадування';
$labels['savingdata'] = 'Збереження даних...';
$labels['role'] = 'Роль';
$labels['availability'] = 'Доступність';
$labels['confirmstate'] = 'Статус';
$labels['roleorganizer'] = 'Організатор';
$labels['rolerequired'] = 'Обов\'язковий';
$labels['roleoptional'] = 'Необов\'язковий';
$labels['sendinvitations'] = 'Запросити';
$labels['itipupdatesubject'] = '"$title" була оновлена';
$labels['taskhistory'] = 'Історія';
$labels['objectchangelog'] = 'Історія змін';
$labels['itipcomment'] = 'Коментар до запрошення/повідомлення';
$labels['andnmore'] = '$nr більше...';
$labels['delegatedto'] = 'Доручено:';
$labels['delegatedfrom'] = 'Доручено від:';
$labels['comment'] = 'Коментарій';
