<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['tags'] = '标签';
$labels['removelist'] = '从列表中移除';
$labels['edit'] = '编辑';
$labels['title'] = '标题';
$labels['description'] = '描述';
$labels['start'] = '开始';
$labels['starttime'] = '开始时间';
$labels['alarms'] = '提醒';
$labels['repeat'] = '循环';
$labels['links'] = '参考';
$labels['status'] = '状态';
$labels['status-cancelled'] = '已取消';
$labels['created'] = '已创建';
$labels['changed'] = '最后更改';
$labels['save'] = '保存';
$labels['cancel'] = '取消';
$labels['tabsummary'] = '汇总';
$labels['tabsharing'] = '分享';
$labels['listname'] = '名称';
$labels['savingdata'] = '保存数据...';
$labels['confirmstate'] = '状态';
$labels['comment'] = '注释';
