<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['tags'] = '标签';
$labels['export'] = '导出';
$labels['exporttitle'] = '导出到ICalendar';
$labels['removelist'] = '从列表中移除';
$labels['edit'] = '编辑';
$labels['delete'] = '删除';
$labels['title'] = '标题';
$labels['description'] = '描述';
$labels['start'] = '开始';
$labels['starttime'] = '开始时间';
$labels['alarms'] = '提醒';
$labels['repeat'] = '循环';
$labels['links'] = '参考';
$labels['status'] = '状态';
$labels['status-cancelled'] = '已取消';
$labels['created'] = '已创建';
$labels['changed'] = '最后更改';
$labels['taskoptions'] = '选项';
$labels['today'] = '今天';
$labels['tomorrow'] = '明天';
$labels['save'] = '保存';
$labels['cancel'] = '取消';
$labels['tabsummary'] = '汇总';
$labels['tabsharing'] = '分享';
$labels['listname'] = '名称';
$labels['showalarms'] = '显示提醒';
$labels['at'] = '在';
$labels['yes'] = '是';
$labels['savingdata'] = '保存数据...';
$labels['role'] = '身份';
$labels['availability'] = '有空';
$labels['confirmstate'] = '状态';
$labels['roleorganizer'] = '组织者';
$labels['rolerequired'] = '必须';
$labels['roleoptional'] = '可选';
$labels['sendinvitations'] = '发送邀请';
$labels['taskhistory'] = '历史';
$labels['comment'] = '注释';
