<?php

/*
+-----------------------------------------------------------------------+
| ./plugins/pop3fetcher/localization/de_DE.inc                          | 
| Language file of roundcube-pop3fetcher plugin							| 
| Copyright (C) 2010-2013, Paolo 'morepaolo' Moretti					|	
| Licensed under the GNU GPL											|
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Paolo Moretti <morepaolo@gmail.com>            	            |
| Translation: Johannes Ries <http://metafakten.de>
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['other_accounts'] = 'Weitere Accounts';
$labels['editaccount'] = 'Account bearbeiten';
$labels['addaccount'] = 'Account erstellen';
$labels['account_email'] = 'E-Mail-Adresse';
$labels['account_username'] = 'Benutzername';
$labels['account_password'] = 'Passwort';
$labels['account_serveraddress'] = 'Server Adresse';
$labels['account_serverport'] = 'Server Port';
$labels['account_usessl'] = 'Verschl&uuml;sselung';
$labels['account_leaveacopy'] = 'Kopien der Nachrichten auf dem Server belassen';
$labels['account_unableconnect'] = "Unable to connect to address";
$labels['account_provider'] = 'Provider';
$labels['test_connection_on_save'] = 'Verbindung beim Speichern testen';
$labels['account_default_folder'] = 'Standard Ordner';
$labels['pop3fetcher_current_version'] = 'Aktuelle Version: ';
$labels['pop3fetcher_latest_version'] = 'Die aktuelle Version ist: ';
$labels['pop3fetcher_updated'] = 'Pop3fetcher ist aktuell.';
$labels['pop3fetcher_outdated'] = "Eine Aktualisierung f&uuml;r Popfetcher ist verf&uuml;gbar.<br />Laden Sie sie hier herunter ";
$labels['account_import_old_messages'] = 'Import old messages';

/* FROM NOW ON: CHECK */
$labels['remoteaccounts'] = 'Remote IMAP Accounts';
$labels['pluginname'] = 'Remote IMAP Accounts';
$labels['plugindescription'] = 'Erlaubt Nutzern Nachrichten in jedem Remote Ordner zu lesen, als w&auml;re er ein lokaler Ordner.';
$labels['account_dn'] = 'Account Name';
$labels['account_id'] = 'Benutzername';
$labels['account_pw'] = 'Passwort';
$labels['account_pw_conf'] = 'Passwort wiederholen';
$labels['account_provider'] = 'Provider';
$labels['add'] = 'Hinzuf&uuml;gen';
$labels['back'] = 'Abbrechen';
$labels['submit'] = 'Speichern';
$labels['archivefolder'] = 'Archiv';
$labels['remotefolders'] = 'Spezialordner';
$labels['description'] = 'Zus&auml;tzliche IMAP-Accounts verwalten';
$labels['dnempty'] = 'Bitte geben Sie einen Namen f&uuml;r den Account an';
$labels['userempty'] = 'Bitte geben Sie ihren Benutzernamen an';
$labels['passwordempty'] = 'Bitte geben Sie ihr Passwort an';
$labels['passwordnotmatch'] = 'Das Passwort ist fehlerhaft';
$labels['hostempty'] = 'Bitte geben Sie eine Serveradresse an (z.B. ssl://imap.gmail.com:993)';
$labels['accountexists'] = 'Dieser Account besteht bereits. Sie werden zum Bearbeitungsmodus weitergeleitet.';
$labels['connectionfailed'] = 'Eine Server-Verbindung konnte nicht hergestellt werden.';

?>
