<?php

/*
+-----------------------------------------------------------------------+
| ./plugins/pop3fetcher/localization/en_GB.inc                          | 
| Language file of roundcube-pop3fetcher plugin							| 
| Copyright (C) 2010-2013, Paolo 'morepaolo' Moretti					|	
| Licensed under the GNU GPL											|
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Paolo Moretti <morepaolo@gmail.com>            	            |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['other_accounts'] = 'Other Accounts';
$labels['editaccount'] = 'Edit Account';
$labels['addaccount'] = 'Add Account';
$labels['account_email'] = 'Email';
$labels['account_username'] = 'Username';
$labels['account_password'] = 'Password';
$labels['account_serveraddress'] = 'Server Address';
$labels['account_serverport'] = 'Server Port';
$labels['account_usessl'] = 'Use SSL';
$labels['account_leaveacopy'] = 'Leave a copy of the message on the server';
$labels['account_unableconnect'] = "Unable to connect to address";
$labels['account_provider'] = 'Provider';
$labels['test_connection_on_save'] = 'Test connection on save';
$labels['account_default_folder'] = 'Default Folder';
$labels['pop3fetcher_current_version'] = 'CURRENT VERSION: ';
$labels['pop3fetcher_latest_version'] = 'Latest version is: ';
$labels['pop3fetcher_updated'] = 'Pop3fetcher is updated to the latest version';
$labels['pop3fetcher_outdated'] = "There's an update available for Pop3fetcher.<br />Download it from ";
$labels['account_import_old_messages'] = 'Import old messages';

/* FROM NOW ON: CHECK */
$labels['remoteaccounts'] = 'Remote IMAP Accounts';
$labels['pluginname'] = 'Remote IMAP Accounts';
$labels['plugindescription'] = 'Allows a user to access messages stored in any remote folder as if it were a local folder.';
$labels['account_dn'] = 'Account Name';
$labels['account_id'] = 'Login ID';
$labels['account_pw'] = 'Password';
$labels['account_pw_conf'] = 'Confirm Password';
$labels['account_provider'] = 'Provider';
$labels['add'] = 'Add';
$labels['back'] = 'Abort';
$labels['submit'] = 'Submit';
$labels['archivefolder'] = 'Archive';
$labels['remotefolders'] = 'Special Folders';
$labels['description'] = 'Manage additional IMAP Accounts.';
$labels['dnempty'] = 'Please enter a name for this account';
$labels['userempty'] = 'Please enter account login ID';
$labels['passwordempty'] = 'Please enter password';
$labels['passwordnotmatch'] = 'Password does not match';
$labels['hostempty'] = 'Please enter host url (f.e. ssl://imap.gmail.com:993)';
$labels['accountexists'] = 'This account already exists. You have been redirected to edit mode.';
$labels['connectionfailed'] = 'Failed to establish connection to remote host.';

?>