<?php

/*
+-----------------------------------------------------------------------+
| ./plugins/pop3fetcher/localization/it_IT.inc                          | 
| Language file of roundcube-pop3fetcher plugin							| 
| Copyright (C) 2010-2013, Paolo 'morepaolo' Moretti					|	
| Licensed under the GNU GPL											|
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Paolo Moretti <morepaolo@gmail.com>            	            |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['other_accounts'] = 'Altri Accounts';
$labels['editaccount'] = 'Modifica Account';
$labels['addaccount'] = 'Aggiungi Account';
$labels['account_email'] = 'Email';
$labels['account_username'] = 'Username';
$labels['account_password'] = 'Password';
$labels['account_serveraddress'] = 'Indirizzo del server (POP3)';
$labels['account_serverport'] = 'Porta (es. 110)';
$labels['account_usessl'] = 'Usa SSL';
$labels['account_leaveacopy'] = 'Lascia una copia dei messaggi sul server';
$labels['account_unableconnect'] = "Impossibile connettersi all'indirizzo";
$labels['account_provider'] = 'Provider';
$labels['test_connection_on_save'] = 'Prova la connessione quando salvi';
$labels['account_default_folder'] = 'Cartella predefinita';
$labels['pop3fetcher_current_version'] = 'VERSIONE CORRENTE: ';
$labels['pop3fetcher_latest_version'] = 'Ultima versione disponibile: ';
$labels['pop3fetcher_updated'] = "Pop3fetcher è già aggiornato all'ultima versione";
$labels['pop3fetcher_outdated'] = "E' disponibile un aggiornamento per Pop3fetcher. Scaricalo da ";
$labels['account_import_old_messages'] = 'Importa vecchi messaggi';

/* FROM NOW ON: CHECK */
$labels['remoteaccounts'] = 'Account IMAP Remoti';
$labels['pluginname'] = 'Account IMAP remoti';
$labels['plugindescription'] = 'Permetti ad un utente di accedere ai messaggi archiviati in ciascuna cartella remota come se fosse locale.';
$labels['account_dn'] = 'Nome Account';
$labels['account_id'] = 'ID Accesso';
$labels['account_pw'] = 'Password';
$labels['account_pw_conf'] = 'Conferma Password';
$labels['account_provider'] = 'Host IMAP';
$labels['add'] = 'Aggiungi';
$labels['back'] = 'Annulla';
$labels['submit'] = 'Invia';
$labels['archivefolder'] = 'Archivio';
$labels['remotefolders'] = 'Cartelle Speciali';
$labels['description'] = 'Genstisci account IMAP aggiuntivi.';
$labels['dnempty'] = 'Per favore inserisci un nome per questo account';
$labels['userempty'] = 'Per favore inserisci il nome utente';
$labels['passwordempty'] = 'Per favore inserisci una password';
$labels['passwordnotmatch'] = 'Le password non corrispondono';
$labels['hostempty'] = 'Per favore inserisci l\'indirizzo dell\'host (es. ssl://imap.gmail.com:993)';
$labels['accountexists'] = 'Account già esistente. Sei stato reindirizzato nella modalità modifica.';
$labels['connectionfailed'] = 'Connessione fallita con l\'host remoto.';

?>