<?php

/*
+-----------------------------------------------------------------------+
| ./plugins/pop3fetcher/localization/nl_NL.inc                          | 
| Language file of roundcube-pop3fetcher plugin							            | 
| Copyright (C) 2010-2013, Paolo 'morepaolo' Moretti					          |	
| Licensed under the GNU GPL											                      |
|                                                                       |
+-----------------------------------------------------------------------+
| Translator: Paolo Moretti <morepaolo@gmail.com>            	          |
| Translator: Djawi de Boer <djawi@djawi.nl>            	              |
| Translator: Thom Heemstra <thom@heemstra.us>                          |
+-----------------------------------------------------------------------+
*/

$labels = array();
$labels['other_accounts'] = 'Andere accounts';
$labels['editaccount'] = 'Account aanpassen';
$labels['addaccount'] = 'Account toevoegen';
$labels['account_email'] = 'E-mailadres';
$labels['account_username'] = 'Gebruikersnaam';
$labels['account_password'] = 'Wachtwoord';
$labels['account_serveraddress'] = 'Serveradres';
$labels['account_serverport'] = 'Serverpoort';
$labels['account_usessl'] = 'SSL gebruiken';
$labels['account_leaveacopy'] = 'Laat een kopie van het bericht achter op de server';
$labels['account_unableconnect'] = "Kan niet met adres verbinden";
$labels['account_provider'] = 'Provider';
$labels['test_connection_on_save'] = 'Verbinding testen na opslaan';
$labels['account_default_folder'] = 'Standaardmap';
$labels['pop3fetcher_current_version'] = 'HUIDIGE VERSIE: ';
$labels['pop3fetcher_latest_version'] = 'Laatste versie is: ';
$labels['pop3fetcher_updated'] = 'Pop3fetcher is bijgewerkt tot de laatste versie';
$labels['pop3fetcher_outdated'] = "Er is een update van Pop3fetcher beschikbaar.<br />U kunt het downloaden op ";
$labels['account_import_old_messages'] = 'Belangrijke oude berichten';

/* FROM NOW ON: CHECK */
$labels['remoteaccounts'] = 'Externe IMAP-accounts';
$labels['pluginname'] = 'Remote IMAP Accounts';
$labels['plugindescription'] = 'Verleent een gebruiker toegang tot berichten uit externe mappen, alsof het een lokale map is.';
$labels['account_dn'] = 'Accountnaam';
$labels['account_id'] = 'Aanmeldings-ID';
$labels['account_pw'] = 'Wachtwoord';
$labels['account_pw_conf'] = 'Wachtwoord bevestigen';
$labels['account_provider'] = 'Provider';
$labels['add'] = 'Toevoegen';
$labels['back'] = 'Annuleren';
$labels['submit'] = 'Indienen';
$labels['archivefolder'] = 'Archief';
$labels['remotefolders'] = 'Speciale mappen';
$labels['description'] = 'Extra IMAP-accounts beheren.';
$labels['dnempty'] = 'Gelieve een naam voor dit account in te voeren';
$labels['userempty'] = 'Gelieve een aanmeldings-ID in te voeren';
$labels['passwordempty'] = 'Gelieve een wachtwoord in te voeren';
$labels['passwordnotmatch'] = 'Wachtwoorden komen niet overeen';
$labels['hostempty'] = 'Gelieve een host-URL in te voeren (bijv. ssl://imap.gmail.com:993)';
$labels['accountexists'] = 'Dit account bestaat reeds. U wordt doorverbonden naar de bewerkmodus.';
$labels['connectionfailed'] = 'Kon geen verbinden maken met externe host.';

?>
