<?php

/*
+-----------------------------------------------------------------------+
| ./plugins/pop3fetcher/localization/ru_RU.inc                          | 
| Language file of roundcube-pop3fetcher plugin				| 
| Copyright (C) 2010-2013, Paolo 'morepaolo' Moretti			|	
| Licensed under the GNU GPL						|
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Alexej Ruseckij <fenuksuh@ya.ru>				|
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['other_accounts'] = 'Другие аккаунты';
$labels['editaccount'] = 'Редактировать аккаунт';
$labels['addaccount'] = 'Добавить аккаунт';
$labels['account_email'] = 'Email';
$labels['account_username'] = 'Логин';
$labels['account_password'] = 'Пароль';
$labels['account_serveraddress'] = 'Адрес сервера';
$labels['account_serverport'] = 'Порт';
$labels['account_usessl'] = 'Использовать SSL';
$labels['account_leaveacopy'] = 'Оставить копию сообщения на сервере';
$labels['account_unableconnect'] = "Не удалось соединиться по адресу";
$labels['account_provider'] = 'Провайдер';
$labels['test_connection_on_save'] = 'Проверить соединение перед сохранением';
$labels['account_default_folder'] = 'Папка по умолчанию';
$labels['pop3fetcher_current_version'] = 'Текущая версия: ';
$labels['pop3fetcher_latest_version'] = 'Последняя версия: ';
$labels['pop3fetcher_updated'] = 'Pop3fetcher обновлён до последней версии';
$labels['pop3fetcher_outdated'] = "Есть обновление для Pop3fetcher.<br />Скачайте с ";


/* FROM NOW ON: CHECK */
$labels['pluginname'] = 'Удалённые IMAP аккаунты';
$labels['plugindescription'] = 'Позволяет пользователю просматривать сообщения, хранящиеся на удалённом сервере, как если бы они были в локальной папке.';
$labels['account_dn'] = 'Имя аккаунта';
$labels['account_id'] = 'Логин ID';
$labels['account_pw'] = 'Пароль';
$labels['account_pw_conf'] = 'Подтвердите пароль';
$labels['account_provider'] = 'Провайдер';
$labels['add'] = 'Добавить';
$labels['back'] = 'Отменить';
$labels['submit'] = 'Отправить';
$labels['archivefolder'] = 'Архив';
$labels['remotefolders'] = 'Специальные папки';
$labels['description'] = 'Настроить дополнительные аккаунты IMAP.';
$labels['dnempty'] = 'Пожалуйста, задайте имя этому аккаунту';
$labels['userempty'] = 'Пожалуйста, введите логин ID';
$labels['passwordempty'] = 'Пожалуйста, введите пароль';
$labels['passwordnotmatch'] = 'Пароли не совпадают';
$labels['hostempty'] = 'Пожалуйста, введите url сервера (напр. ssl://imap.gmail.com:993)';
$labels['accountexists'] = 'Такой аккаунт уже существует. Перенаправляю на редактирование.';
$labels['connectionfailed'] = 'Не удалось установить соединение с удалённым сервером.';

?>