<?php

/*
+-----------------------------------------------------------------------+
| ./plugins/pop3fetcher/localization/zh_TW.inc                          |
| Language file of roundcube-pop3fetcher plugin                         |
| Copyright (C) 2010-2013, Paolo 'morepaolo' Moretti                    |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Anhsiou Tsai <anhsiou@gmail.com>                              |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['other_accounts'] = '其他郵件帳號';
$labels['editaccount'] = '編輯帳號';
$labels['addaccount'] = '新增帳號';
$labels['account_email'] = '電子郵件';
$labels['account_username'] = '登入帳號';
$labels['account_password'] = '密碼';
$labels['account_serveraddress'] = '伺服器位址';
$labels['account_serverport'] = '伺服器埠';
$labels['account_usessl'] = '使用 SSL';
$labels['account_leaveacopy'] = '保留伺服器上的郵件';
$labels['account_unableconnect'] = "無法連接伺服器";
$labels['account_provider'] = '郵件服務供應商';
$labels['test_connection_on_save'] = '儲存後測試是否連通';
$labels['account_default_folder'] = '預設資料夾';
$labels['pop3fetcher_current_version'] = '目前版本： ';
$labels['pop3fetcher_latest_version'] = '最新的版本是： ';
$labels['pop3fetcher_updated'] = 'Pop3fetcher已經更新到最新的版本';
$labels['pop3fetcher_outdated'] = "Pop3fetcher有更新的版本，<br />可以從以下網址下載 ";


/* FROM NOW ON: CHECK */
$labels['pluginname'] = '其他 IMAP 帳號';
$labels['plugindescription'] = '允許使用者存取儲存在其他遠端資料夾的郵件，只要it were a local folder.';
$labels['account_dn'] = '顯示名稱';
$labels['account_id'] = '登入帳號';
$labels['account_pw'] = '密碼';
$labels['account_pw_conf'] = '確認密碼';
$labels['account_provider'] = '郵件服務供應商';
$labels['add'] = '新增';
$labels['back'] = '取消';
$labels['submit'] = '送出';
$labels['archivefolder'] = '封存';
$labels['remotefolders'] = '特殊資料夾';
$labels['description'] = '管理額外的 IMAP 帳號';
$labels['dnempty'] = '請給這個帳號一個名稱';
$labels['userempty'] = '請輸入登入帳號';
$labels['passwordempty'] = '請輸入密碼';
$labels['passwordnotmatch'] = '密碼不一致';
$labels['hostempty'] = '請輸入主機網址 (f.e. ssl://imap.gmail.com:993)';
$labels['accountexists'] = '這個帳號已經存在，你將被導引至修改頁面。';
$labels['connectionfailed'] = '連接遠端主機失敗';

?>
