<?php
$labels = array();
$labels['automaticallycollected']  = 'Acollechao automáticamente';
$labels['useautoabook']  = 'Usar llibru de direiciones automáticu';
$labels['useforcompletion'] = 'Usar direiciones acollechaes pal autocompletáu automáticamente';
$labels['contactremoved'] = 'Contautu(os) desaniciáu(os) del llibru de direiciones automáticu';
$labels['contactmoved'] = 'Contautu(os) movíu(os) del llibru de direiciones automáticu';
?>
