<?php
$labels = array();
$labels['automaticallycollected']  = 'Yığılmış ünvanlar';
$labels['useautoabook']  = 'Yığılmış ünvanları istifadə et';
$labels['useforcompletion'] = 'Avtobitmə üçün avtomatik yığılmış ünvanları istifadə et';
$labels['contactremoved'] = 'Kontakt(lar) avtomatik ünvan kitabçasından silindi';
$labels['contactmoved'] = 'Kontakt(lar) avtomatik ünvan kitabçasından köçürüldü';
?>
