<?php
$labels = array();
$labels['automaticallycollected']  = 'Аўтаматычна сабраныя';
$labels['useautoabook']  = 'Выкарыстоўваць аўтаматычную адрасную кнігу';
$labels['useforcompletion'] = 'Выкарыстоўваць аўтаматычна сабраныя адрасы для аўтазапаўнення';
$labels['contactremoved'] = 'Кантакт(ы), выдаленыя з аўтаматычнай адраснай кнігі';
$labels['contactmoved'] = 'Кантакт(ы), перамешчаныя з аўтаматычнай адраснай кнігі';
?>
