<?php
$labels = array();
$labels['automaticallycollected']  = 'Събрани адреси';
$labels['useautoabook']  = 'Използване на автоматична адресна книга';
$labels['useforcompletion'] = 'Използване на автоматично събраните адреси за автоматично довършване';
$labels['contactremoved'] = 'Изтрит от автоматичната адресна книга контакт(и)';
$labels['contactmoved'] = 'Преместен от автоматичната адресна книга контакт(и)';
?>
