<?php
$labels = array();
$labels['automaticallycollected']  = 'Recopilats automàticament';
$labels['useautoabook']  = 'Utilitza la llibreta d\'adreces automàticament';
$labels['useforcompletion'] = 'Utilitza les adreces recopilades automàticament per a autocompletar';
$labels['contactremoved'] = 'Contacte(s) suprimits de la llibreta d\'adreces automàtica';
$labels['contactmoved'] = 'Contacte(s) moguts de la llibreta d\'adreces automàtica';
?>
