<?php
$labels = array();
$labels['automaticallycollected']  = 'Automaticky zaznamenané';
$labels['useautoabook']  = 'Používat automatický adresář';
$labels['useforcompletion'] = 'Používat adresy z automatického adresáře pro doplňování';
$labels['contactremoved'] = 'Kontakt(y) byl odstraněn(y) z automatického adresáře';
$labels['contactmoved'] = 'Kontakt(y) byl přesunut(y) z automatického adresáře';
?>
