<?php
$labels = array();
$labels['automaticallycollected']  = 'Casglwyd yn Awtomatig';
$labels['useautoabook']  = 'Defnyddio llyfr cyfeiriadau awtomatig';
$labels['useforcompletion'] = 'Defnyddio cyfeiriadau casglwyd yn awtomatig ar gyfer awtogwblhau';
$labels['contactremoved'] = 'Cysylltiadau wedi eu dileu o\'r llyfr cyfeiriadau awtomatig';
$labels['contactmoved'] = 'Cysylltiadau wedi eu symud o\'r llyfr cyfeiriadau awtomatig';
?>
