<?php
$labels = array();
$labels['automaticallycollected']  = 'Αυτόματα συλλεγμένες';
$labels['useautoabook']  = 'Χρήση αυτόματου βιβλίου διευθύνσεων';
$labels['useforcompletion'] = 'Χρήση αυτόματα συλλεγμένων διευθύνσεων για αυτόματη συμπλήρωση';
$labels['contactremoved'] = 'Οι επαφές διαγράφηκαν από το αυτόματο βιβλίο διευθύνσεων';
$labels['contactmoved'] = 'Οι επαφές μετακινήθηκαν από το αυτόματο βιβλίο επαφών';
?>
