<?php
$labels = array();

/*
 +-----------------------------------------------------------------------+
 | localization/en_EN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels['automaticallycollected'] = 'Automatically Collected';
$labels['useautoabook'] = 'Use automatic address book';
$labels['useforcompletion'] = 'Use automatically collected addresses for autocompletion';
$labels['contactremoved'] = 'Contact(s) deleted from automatic address book';
$labels['contactmoved'] = 'Contact(s) moved from automatic address book';

?>
