<?php
$labels = array();
$labels['automaticallycollected']  = 'Recolectadas automáticamente';
$labels['useautoabook']  = 'Usar libreta de direcciones automática';
$labels['useforcompletion'] = 'Usar direcciones recolectadas automáticamente en autocompletado';
$labels['contactremoved'] = 'Contacto(s) eliminados de la libreta automática de direcciones';
$labels['contactmoved'] = 'Contacto(s) movidos de la libreta automática de direcciones';
?>
