<?php
$labels = array();
$labels['automaticallycollected']  = 'Recolectado automaticamente';
$labels['useautoabook']  = 'Usar libreta automatica de direcciones';
$labels['useforcompletion'] = 'Usar las direcciones recolectadas automaticamente para autocompletar';
$labels['contactremoved'] = 'Contacto(s) eliminados de la libreta automatica de direcciones';
$labels['contactmoved'] = 'Contacto(s) movidos desde la libreta automatica de direcciones';
?>
