<?php
$labels = array();
$labels['automaticallycollected']  = 'Automáticamente colectados';
$labels['useautoabook']  = 'Utilizar la libreta de direcciones automática';
$labels['useforcompletion'] = 'Utilizar las direcciones automáticamente colectadas para la autocompletación';
$labels['contactremoved'] = 'Contacto(s) eliminado(s) de la libreta de direcciones automática';
$labels['contactmoved'] = 'Contacto(s) movido(s) de la libreta de direcciones automática';
?>
