<?php
$labels = array();
$labels['automaticallycollected']  = 'Automatikoki bilduta';
$labels['useautoabook']  = 'Erabili helbide-liburu automatikoa';
$labels['useforcompletion'] = 'Erabili automatikoki bildutako helbideak auto osatzerako';
$labels['contactremoved'] = 'Kontaktua(k) ezabatuta helburu-liburu automatikotik';
$labels['contactmoved'] = 'Kontaktua(k) mugituta helburu-liburu automatikotik';
?>
