<?php
$labels = array();
$labels['automaticallycollected']  = 'به صورت خودکار جمع آوری شد';
$labels['useautoabook']  = 'از لیست نشانی خودکار استفاده شود';
$labels['useforcompletion'] = 'از آدرس های جمع آوری شده به صورت خودکار برای تکمیل خودکار استفاده کنید';
$labels['contactremoved'] = 'نشانی(های) پاک شده از دفترچه نشانی خودکار';
$labels['contactmoved'] = 'نشانی(های) منتقل شده از دفترچه نشانی خودکار';
?>
