<?php
$labels = array();
$labels['automaticallycollected']  = 'Automaattisesti kerätty';
$labels['useautoabook']  = 'Käytä automaattista osoitekirjaa';
$labels['useforcompletion'] = 'Käytä automaattisesti kerättyjä osoitteita automaattitäydennystä varten';
$labels['contactremoved'] = 'Automaattisesta osoitekirjasta poistetut yhteystiedot';
$labels['contactmoved'] = 'Automaattisesta osoitekirjasta siirretyt yhteystiedot';
?>
