<?php
$labels = array();
$labels['automaticallycollected']  = 'Innsamla sjálvirkandi';
$labels['useautoabook']  = 'Brúka sjálvvirkandi búðstaðar bók';
$labels['useforcompletion'] = 'Nýt sjálvirkandi innsamlaðar teldupostir til sjálvirkandi innseting';
$labels['contactremoved'] = 'Sambindingarliður(ir) strikaður frá búðstaðar bók';
$labels['contactmoved'] = 'Sambindingarliður(ir) fluttir frá búðstaðar bók';
?>
