<?php
$labels = array();
$labels['automaticallycollected']  = 'Collectées automatiquement';
$labels['useautoabook']  = 'Utiliser le carnet d\'adresses automatique';
$labels['useforcompletion'] = 'Utiliser les adresses collectées automatiquement pour l\'autocomplétion';
$labels['contactremoved'] = 'Contact(s) supprimé(s) de la collecte automatique';
$labels['contactmoved'] = 'Contact(s) déplacé(s) de la collecte automatique';
?>
