<?php
$labels = array();
$labels['automaticallycollected']  = 'Enderezos recentes';
$labels['useautoabook']  = 'Gardar automáticamente os enderezos aos que se envía correo';
$labels['useforcompletion'] = 'Usar os enderezos recentes para autocompletar';
$labels['contactremoved'] = 'Contacto(s) eliminado(s) da Axenda de enderezos automática';
$labels['contactmoved'] = 'Contacto(s) engadido(s) á Axenda de enderezos';
?>
