<?php
$labels = array();
$labels['automaticallycollected']  = 'Automaticamente colligite';
$labels['useautoabook']  = 'Usar le adressario automatic';
$labels['useforcompletion'] = 'Usar adresses automaticamente colligite pro autocompletion';
$labels['contactremoved'] = 'Contacto(s) delite del adressario automatic';
$labels['contactmoved'] = 'Contacto(s) displaciate ab le adressario automatic';
?>
