<?php
$labels = array();
$labels['automaticallycollected']  = 'Automatesch gesammelt';
$labels['useautoabook']  = 'Automatescht Adressbuch benotzen';
$labels['useforcompletion'] = 'Automatesch gesammelt Adressen an der automatescher Vervollstännegung benotzen';
$labels['contactremoved'] = 'Kontakt(er) aus dem automateschen Adressbuch geläscht';
$labels['contactmoved'] = 'Kontakt(er) aus dem automateschen Adressbuch geréckelt';
?>
