<?php
$labels = array();
$labels['automaticallycollected']  = 'Pievienoti automātiski';
$labels['useautoabook']  = 'Lietot automātisko adrešu grāmatu';
$labels['useforcompletion'] = 'Automātiskajai pabeigšanai lietot automātiski pievienotās adreses';
$labels['contactremoved'] = 'Kontakti izdzēsti no automātiskās adrešu grāmatas';
$labels['contactmoved'] = 'Kontakti pārvietoti no automātiskās adrešu grāmatas';
?>
