<?php
$labels = array();

/*
 +-----------------------------------------------------------------------+
 | localization/nb_NB/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Tobias V. Langhoff <spug@thespug.net>                         |
 +-----------------------------------------------------------------------+
*/

$labels['automaticallycollected'] = 'Automatisk innsamlet';
$labels['useautoabook'] = 'Bruk automatisk adressebok';
$labels['useforcompletion'] = 'Bruk automatisk innsamlede adresser i autofullføring';
$labels['contactremoved'] = 'Kontakt(er) slettet fra den automatiske adresseboka';
$labels['contactmoved'] = 'Kontakt(er) flyttet fra den automatiske adresseboka';

?>
