<?php
$labels = array();
$labels['automaticallycollected']  = 'Automatisch verzameld';
$labels['useautoabook']  = 'Gebruik automatisch adresboek';
$labels['useforcompletion'] = 'Gebruik automatisch verzamelde adressen voor automatisch aanvullen';
$labels['contactremoved'] = 'Contact(en) verwijderd uit het automatische adresboek';
$labels['contactmoved'] = 'Contact(en) verplaatst uit het automatische adresboek';
?>
