<?php
$labels = array();
$labels['automaticallycollected']  = 'Automatycznie zbierane';
$labels['useautoabook']  = 'Użyj automatycznej książki adresowej';
$labels['useforcompletion'] = 'Użyj automatycznie zebrane adresy do automatycznego uzupełniania';
$labels['contactremoved'] = 'Kontakt(y) usunięty z automatycznej książki adresowej';
$labels['contactmoved'] = 'Kontakt(y) przeniesiony z automatycznej książki adresowej';
?>
