<?php
$labels = array();
$labels['automaticallycollected']  = 'Coletado automaticamente';
$labels['useautoabook']  = 'Usar catálogo de endereço automático';
$labels['useforcompletion'] = 'Usar endereços coletados automaticamente para autocompletar';
$labels['contactremoved'] = 'Contato(s) excluído(s) do catálogo de endereços automático';
$labels['contactmoved'] = 'Contato(s) movido(s) do catálogo de endereços automático';
?>
