<?php
$labels = array();
$labels['automaticallycollected']  = 'Coletados automaticamente';
$labels['useautoabook']  = 'Usar livro de endereços automático';
$labels['useforcompletion'] = 'Usar endereços coletados automaticamente para autocompletar';
$labels['contactremoved'] = 'Contacto(s) eliminado(s) do livro de endereços automático';
$labels['contactmoved'] = 'Contacto(s) movido(s) para o livro de endereços automático';
?>
