<?php
$labels = array();
$labels['automaticallycollected']  = 'Automaticky zozbierané';
$labels['useautoabook']  = 'Použiť automatický adresár';
$labels['useforcompletion'] = 'Použiť automaticky zozbierané adresy na automatické dokončovanie';
$labels['contactremoved'] = 'Kontakty, ktoré boli vymazané z automatického adresára';
$labels['contactmoved'] = 'Kontakty, ktoré boli presunuté z automatického adresára';
?>
