<?php
$labels = array();
$labels['automaticallycollected']  = 'Автоматично зібрані';
$labels['useautoabook']  = 'Використовувати автоматичну адресну книгу';
$labels['useforcompletion'] = 'Використовувати автоматично зібрані адреси для автодоповнення';
$labels['contactremoved'] = 'Контакт(и) вилучено з автоматичої адресної книги';
$labels['contactmoved'] = 'Контакт(и) переміщено з автоматичої адресної книги';
?>
