<?php

$labels = array();

// config
$labels['default_view'] = 'Výchozí pohled';
$labels['time_format'] = 'Formát data';
$labels['timeslots'] = 'Slotů na hodinu';
$labels['first_day'] = 'První den v týdnu';

// preferences
$labels['default_view'] = 'Výchozí pohled';
$labels['time_format'] = 'Formát času';
$labels['timeslots'] = 'Slotů na hodinu';
$labels['first_day'] = 'První den týdne';
$labels['first_hour'] = 'První hodina k zobrazení';
$labels['workinghours'] = 'Pracovní hodiny';
$labels['add_category'] = 'Přidat kategorii';
$labels['remove_category'] = 'Odstranit kategorii';
$labels['defaultcalendar'] = 'Vytvářet nové události v';
$labels['eventcoloring'] = 'Barvy událostí';
$labels['coloringmode0'] = 'Podle kalendáře';
$labels['coloringmode1'] = 'Podle kategorie';
$labels['coloringmode2'] = 'Kalendář pro orámování, kategorie pro obsah';
$labels['coloringmode3'] = 'Kategorie pro orámování, kalendář pro obsah';

// calendar
$labels['calendar'] = 'Kalendář';
$labels['calendars'] = 'Kalendáře';
$labels['category'] = 'Kategorie';
$labels['categories'] = 'Kategorie';
$labels['createcalendar'] = 'Vytvořit nový kalendář';
$labels['editcalendar'] = 'Upravit vlastnosti kalendáře';
$labels['name'] = 'Název';
$labels['color'] = 'Barva';
$labels['day'] = 'Den';
$labels['week'] = 'Týden';
$labels['month'] = 'Měsíc';
$labels['agenda'] = 'Agenda';
$labels['new'] = 'Nová';
$labels['new_event'] = 'Nová událost';
$labels['edit_event'] = 'Upravit událost';
$labels['edit'] = 'Upravit';
$labels['save'] = 'Uložit';
$labels['remove'] = 'Odstranit';
$labels['cancel'] = 'Storno';
$labels['select'] = 'Vybrat';
$labels['print'] = 'Tisk';
$labels['printtitle'] = 'Vytisknout kalendáře';
$labels['title'] = 'Souhrn';
$labels['description'] = 'Popis';
$labels['all-day'] = 'celý den';
$labels['export'] = 'Exportovat do ICS';
$labels['exporttitle'] = 'Exportovat souhrn do ICS';
$labels['location'] = 'Místo';
$labels['date'] = 'Datum';
$labels['start'] = 'Začátek';
$labels['end'] = 'Konec';
$labels['selectdate'] = 'Vyberte datum';
$labels['freebusy'] = 'Zobrazovat časový úsek jako';
$labels['free'] = 'volno';
$labels['busy'] = 'obsazeno';
$labels['outofoffice'] = 'mimo kancelář';
$labels['tentative'] = 'nezávazně';
$labels['priority'] = 'Priorita';
$labels['sensitivity'] = 'Soukromí';
$labels['public'] = 'veřejné';
$labels['private'] = 'soukromé';
$labels['confidential'] = 'důvěrné';
$labels['alarms'] = 'Připomenutí';
$labels['generated'] = 'vygenerováno';
$labels['printdescriptions'] = 'Vytisknout popisy';
$labels['parentcalendar'] = 'Vložit dovnitř';
$labels['searchearlierdates'] = '« Hledat dřívější události';
$labels['searchlaterdates'] = 'Hledat pozdější události »';
$labels['andnmore'] = 'dalších $nr...';
$labels['togglerole'] = 'Klikněte k přepnutí role';
$labels['createfrommail'] = 'Uložit jako událost';
$labels['importevents'] = 'Importovat události';
$labels['importrange'] = 'Události od';
$labels['onemonthback'] = '1 měsíc nazpátek';
$labels['nmonthsback'] = '$nr měsíců nazpátek';
$labels['showurl'] = 'Ukázat URL kalendáře';
$labels['showurldescription'] = 'Tuto adresu použijte pro přístup (jen ke čtení) ke kalendáři z jiných aplikací. Můžete ji zkopírovat a vložit do jakéhokoli kalendářového softwaru, který podporuje formát iCal.';

// agenda view
$labels['listrange'] = 'Rozsah k zobrazení:';
$labels['listsections'] = 'Rozdělit na:';
$labels['smartsections'] = 'Chytré sekce';
$labels['until'] = 'do';
$labels['today'] = 'Dnes';
$labels['tomorrow'] = 'Zítra';
$labels['thisweek'] = 'Tento týden';
$labels['nextweek'] = 'Příští týden';
$labels['thismonth'] = 'Tento měsíc';
$labels['nextmonth'] = 'Příští měsíc';
$labels['weekofyear'] = 'Týden';
$labels['pastevents'] = 'Minulost';
$labels['futureevents'] = 'Budoucnost';

// alarm/reminder settings
$labels['showalarms'] = 'Zobrazit upozornění';
$labels['defaultalarmtype'] = 'Výchozí nastavení připomenutí';
$labels['defaultalarmoffset'] = 'Výchozí čas připomenutí';

// attendees
$labels['attendee'] = 'Účastník';
$labels['role'] = 'Role';
$labels['availability'] = 'Dost.';
$labels['confirmstate'] = 'Stav';
$labels['addattendee'] = 'Přidat účastníka';
$labels['roleorganizer'] = 'Organizátor';
$labels['rolerequired'] = 'Povinný';
$labels['roleoptional'] = 'Nepovinný';
$labels['roleresource'] = 'Prostředek';
$labels['availfree'] = 'volno';
$labels['availbusy'] = 'obsazeno';
$labels['availunknown'] = 'neznámý';
$labels['availtentative'] = 'nezávazně';
$labels['availoutofoffice'] = 'mimo kancelář';
$labels['scheduletime'] = 'Najít dostupnost';
$labels['sendinvitations'] = 'Poslat pozvánky';
$labels['sendnotifications'] = 'Uvědomit účastníky o změnách';
$labels['sendcancellation'] = 'Uvědomit účastníky o zrušení události';
$labels['onlyworkinghours'] = 'Najít dostupnost v mé pracovní době';
$labels['reqallattendees'] = 'Povinní/všichni účastníci';
$labels['prevslot'] = 'Předchozí slot';
$labels['nextslot'] = 'Další slot';
$labels['noslotfound'] = 'Nelze najít volný slot';
$labels['invitationsubject'] = 'Byl(a) jste pozván(a) na událost "$title"';
$labels['invitationmailbody'] = "*\$title*\n\nKdy: \$date\n\nPozváni: \$attendees\n\nPodrobnosti o události najdete v přiloženém souboru typu iCalendar. Můžete si ho naimportovat do kalendářového programu.";
$labels['invitationattendlinks'] = "Pokud váš poštovní klient nepodporuje pozvánky iTip, použijte prosím následující odkaz k potvrzení nebo odmítnutí pozvání:\n\$url";
$labels['eventupdatesubject'] = 'Událost "$title" byla aktualizována';
$labels['eventupdatesubjectempty'] = 'Událost, která se vás týká, byla aktualizována';
$labels['eventupdatemailbody'] = "*\$title*\n\nKdy: \$date\n\nPozváni: \$attendees\n\nPodrobnosti o aktualizované události najdete v přiloženém souboru typu iCalendar. Můžete si ho naimportovat do kalendářového programu.";
$labels['eventcancelsubject'] = 'Událost "$title" byla zrušena';
$labels['eventcancelmailbody'] = "*\$title*\n\nKdy: \$date\n\nPozváni: \$attendees\n\nUdálost byla zrušena organizátorem (\$organizer).\n\nPodrobnosti najdete v přiloženém souboru ve formátu iCalendar.";

// invitation handling
$labels['itipinvitation'] = 'Pozvání na událost';
$labels['itipupdate'] = 'Aktualizace události';
$labels['itipcancellation'] = 'Zrušeno:';
$labels['itipreply'] = 'Odpověď na';
$labels['itipaccepted'] = 'Potvrdit';
$labels['itiptentative'] = 'Možná';
$labels['itipdeclined'] = 'Odmítnout';
$labels['itipsubjectaccepted'] = '$name potvrdil(a) účas na události "$title"';
$labels['itipsubjecttentative'] = '$name nezávazně potvrdil(a) účast na události "$title"';
$labels['itipsubjectdeclined'] = '$name odmítl(a) účast na události "$title"';
$labels['itipmailbodyaccepted'] = "\$sender přijal(a) pozvání na tuto událost:\n\n*\$title*\n\nKdy: \$date\n\nPozváni: \$attendees";
$labels['itipmailbodytentative'] = "\$sender nezávazně přijal(a) pozvání na tuto událost:\n\n*\$title*\n\nKdy: \$date\n\nPozváni: \$attendees";
$labels['itipmailbodydeclined'] = "\$sender odmítl(a) pozvání na tuto událost:\n\n*\$title*\n\nKdy: \$date\n\nPozváni: \$attendees";
$labels['itipdeclineevent'] = 'Opravdu chcete odmítnout pozvání na tuto událost?';
$labels['importtocalendar'] = 'Uložit do kalendáře';
$labels['removefromcalendar'] = 'Odstranit z kalendáře';
$labels['updateattendeestatus'] = 'Aktualizovat stav účastníka';
$labels['acceptinvitation'] = 'Chcete přijmout toto pozvání (potvrdit účast)?';
$labels['youhaveaccepted'] = 'Přijal(a) jste toto pozvání';
$labels['youhavetentative'] = 'Nezávazně jste přijal(a) toto pozvání';
$labels['youhavedeclined'] = 'Odmítl(a) jste toto pozvání';
$labels['notanattendee'] = 'Nejste na seznamu účastníků této události';
$labels['eventcancelled'] = 'Tato událost byla zrušena';
$labels['saveincalendar'] = 'uložit do';

// event dialog tabs
$labels['tabsummary'] = 'Souhrn';
$labels['tabrecurrence'] = 'Opakování';
$labels['tabattendees'] = 'Účastníci';
$labels['tabattachments'] = 'Přílohy';
$labels['tabsharing'] = 'Sdílení';

// messages
$labels['deleteventconfirm'] = 'Opravdu chcete smazat tuto událost?';
$labels['deletecalendarconfirm'] = 'Opravdu chcete smazat tento kalendář se všemi událostmi?';
$labels['savingdata'] = 'Ukládám data...';
$labels['errorsaving'] = 'Nelze uložit změny.';
$labels['operationfailed'] = 'Požavovaná operace selhala.';
$labels['invalideventdates'] = 'Vložená data nejsou platná! Zkontrolujte prosím zadávané údaje.';
$labels['invalidcalendarproperties'] = 'Neplatné vlastnosti kalendáře! Vložte prosím platné jméno.';
$labels['searchnoresults'] = 'Ve vybraných kalendářích nebyly nalezeny žádné události.';
$labels['successremoval'] = 'Událost byla úspěšně smazána.';
$labels['successrestore'] = 'Událost byla úspěšně obnovena.';
$labels['errornotifying'] = 'Nelze odeslat notifikace účastníkům události';
$labels['errorimportingevent'] = 'Nelze naimportovat událost';
$labels['newerversionexists'] = 'Existuje již novější verze této události! Operace byla zrušena.';
$labels['nowritecalendarfound'] = 'Nebyl nalezen žádný kalendář, do kterého by šlo uložit tuto událost.';
$labels['importedsuccessfully'] = 'Událost byla úspěšně přidána do kalendáře \'$calendar\'';
$labels['attendeupdateesuccess'] = 'Stav účastníka byl úspěšně aktualizován';
$labels['itipsendsuccess'] = 'Pozvánky byly rozeslány účastníkům.';
$labels['itipresponseerror'] = 'Nelze odeslat odpověď na tuto pozvánku';
$labels['itipinvalidrequest'] = 'Tato pozvánka již není platná';
$labels['sentresponseto'] = 'Odpověď na pozvánku byla úspěšně odeslána na adresu $mailto';
$labels['localchangeswarning'] = 'Chystáte se provést změny, které se projeví jen ve vašem vlastním kalendáři a nelze je poslat organizátorovi události.';
$labels['importsuccess'] = 'Úspěšně importováno $nr událostí';
$labels['importnone'] = 'Nebyly nalezeny žádné události k importu';
$labels['importerror'] = 'Při importu došlo k chybě';
$labels['aclnorights'] = 'Nemáte administrátorská práva k tomuto kalendáři.';

// recurrence form
$labels['repeat'] = 'Opakování';
$labels['frequency'] = 'Opakovat';
$labels['never'] = 'nikdy';
$labels['daily'] = 'denně';
$labels['weekly'] = 'týdně';
$labels['monthly'] = 'měsíčně';
$labels['yearly'] = 'ročně';
$labels['every'] = 'Každý';
$labels['days'] = 'den (dny)';
$labels['weeks'] = 'týden (týdny)';
$labels['months'] = 'měsíc(e/ů)';
$labels['years'] = 'rok(y/ů) v:';
$labels['bydays'] = ' ';
$labels['untildate'] = 'do';
$labels['each'] = 'Každý';
$labels['onevery'] = 'Vždy v';
$labels['onsamedate'] = 'Ve stejné datum';
$labels['forever'] = 'trvale';
$labels['recurrencend'] = 'do';
$labels['forntimes'] = 'jen $nrkrát';
$labels['first'] = 'první';
$labels['second'] = 'druhý';
$labels['third'] = 'třetí';
$labels['fourth'] = 'čtvrtý';
$labels['last'] = 'poslední';
$labels['dayofmonth'] = 'Den v měsíci';

$labels['changeeventconfirm'] = 'Změnit událost';
$labels['removeeventconfirm'] = 'Odstranit událost';
$labels['changerecurringeventwarning'] = 'Toto je opakovaná událost. Chcete upravit jen toto konání, toto a všechna následující konání, úplně všechna konání nebo uložit událost jako novou?';
$labels['removerecurringeventwarning'] = 'Toto je opakovaná událost. Chcete odstranit jen toto konání, toto a následující konání nebo úplně všechna konání této události?';
$labels['currentevent'] = 'Aktuální';
$labels['futurevents'] = 'Budoucí';
$labels['allevents'] = 'Všechny';
$labels['saveasnew'] = 'Uložit jako novou';

