<?php

$labels = array();

// preferences
$labels['default_view'] = 'Vaikevaade';
$labels['time_format'] = 'Aja vorming';
$labels['timeslots'] = 'Ajaühikuid päevas';
$labels['first_day'] = 'Esimene päev';
$labels['first_hour'] = 'Esimene tund';
$labels['workinghours'] = 'Tööaeg';
$labels['add_category'] = 'Lisa kategooria';
$labels['remove_category'] = 'Kustuta kategooria';
$labels['defaultcalendar'] = 'Loo uued sündmused';
$labels['eventcoloring'] = 'Sündmuste värvid';
$labels['coloringmode0'] = 'Vastavalt kalendrile';
$labels['coloringmode1'] = 'Vastavalt kategooriale';
$labels['coloringmode2'] = 'Kalender väljaspool, kategooria sisul';
$labels['coloringmode3'] = 'Kategooria väljaspool, kalender sisul';

// calendar
$labels['calendar'] = 'Kalender';
$labels['calendars'] = 'Kalendrid';
$labels['category'] = 'Kategooria';
$labels['categories'] = 'Kategooriad';
$labels['createcalendar'] = 'Uus kalender';
$labels['editcalendar'] = 'Muuda seadeid';
$labels['name'] = 'Nimi';
$labels['color'] = 'Värv';
$labels['day'] = 'Päev';
$labels['week'] = 'Nädal';
$labels['month'] = 'Kuu';
$labels['agenda'] = 'Agenda';
$labels['new'] = 'Uus';
$labels['new_event'] = 'Uus sündmus';
$labels['edit_event'] = 'Muuda sündmust';
$labels['edit'] = 'Redigeeri';
$labels['save'] = 'Salvesta';
$labels['remove'] = 'Kustuta';
$labels['cancel'] = 'Tühista';
$labels['select'] = 'Märgi';
$labels['print'] = 'Trüki';
$labels['printtitle'] = 'Trüki kalendrid';
$labels['title'] = 'Kokkuvõte';
$labels['description'] = 'Selgitus';
$labels['all-day'] = 'kogu päev';
$labels['export'] = 'Ekspordi';
$labels['exporttitle'] = 'Ekspordi iCalendar';
$labels['location'] = 'Askukoht';
$labels['date'] = 'Kuupäev';
$labels['start'] = 'Algus';
$labels['end'] = 'Lõpp';
$labels['selectdate'] = 'Vali kuupäev';
$labels['freebusy'] = 'Näita mind';
$labels['free'] = 'vabana';
$labels['busy'] = 'hõivatuna';
$labels['outofoffice'] = 'kontorist eemal';
$labels['tentative'] = 'ei tea';
$labels['priority'] = 'Prioriteet';
$labels['sensitivity'] = 'Privaatsus';
$labels['public'] = 'avalik';
$labels['private'] = 'varjatud';
$labels['confidential'] = 'konfidentsiaalne';
$labels['alarms'] = 'Meeldetuletus';
$labels['generated'] = 'loodud';
$labels['printdescriptions'] = 'Väljuta kirjeldus';
$labels['parentcalendar'] = 'Sisesta';
$labels['searchearlierdates'] = '« Otsi varasemaid sündmusi';
$labels['searchlaterdates'] = 'Otsi hilisemaid sündmusi »';
$labels['andnmore'] = '$nr rohkem...';
$labels['togglerole'] = 'Kliki rolli muutmiseks';
$labels['createfrommail'] = 'Salvesta sündmusena';
$labels['importevents'] = 'Impordi sündmused';
$labels['importrange'] = 'Sündmused alates';
$labels['onemonthback'] = '1 kuu tagasi';
$labels['nmonthsback'] = '$nr kuud tagasi';
$labels['showurl'] = 'Näita kalendi URLi';
$labels['showurldescription'] = 'Kasuta seda aadressi kalendri lugemisõiguse andmiseks iCal vormingus.';

// agenda view
$labels['listrange'] = 'Näita ajavahemikku:';
$labels['listsections'] = 'Jaga:';
$labels['smartsections'] = 'nutikad osad';
$labels['until'] = 'kuni';
$labels['today'] = 'täna';
$labels['tomorrow'] = 'homme';
$labels['thisweek'] = 'see nädal';
$labels['nextweek'] = 'järgmine nädal';
$labels['thismonth'] = 'Sel kuul';
$labels['nextmonth'] = 'Järgmisel kuul';
$labels['weekofyear'] = 'Nädal aastas';
$labels['pastevents'] = 'Möödunud';
$labels['futureevents'] = 'Tulevased';

// alarm/reminder settings
$labels['showalarms'] = 'Näita meeldetuletusi';
$labels['defaultalarmtype'] = 'Meeldetuletuse vaiketüüp';
$labels['defaultalarmoffset'] = 'Meeldetuletuse vaikeaeg';

// attendees
$labels['attendee'] = 'Ósavõtja';
$labels['role'] = 'Roll';
$labels['availability'] = 'Saadavus';
$labels['confirmstate'] = 'Staatus';
$labels['addattendee'] = 'Lisa osaleja';
$labels['roleorganizer'] = 'Korraldaja';
$labels['rolerequired'] = 'Vajalik';
$labels['roleoptional'] = 'Teised';
$labels['roleresource'] = 'Ressurss';
$labels['availfree'] = 'Vaba';
$labels['availbusy'] = 'Hõivatud';
$labels['availunknown'] = 'Teadmata';
$labels['availtentative'] = 'Tinglik';
$labels['availoutofoffice'] = 'Kontorist eemal';
$labels['scheduletime'] = 'Otsi saadavust';
$labels['sendinvitations'] = 'Saada kutsed';
$labels['sendnotifications'] = 'Anna osavõtjaile muutustest teada';
$labels['sendcancellation'] = 'Anna osavõtjaile tühistamisest teada';
$labels['onlyworkinghours'] = 'Leia vaba aeg minu tööajast';
$labels['reqallattendees'] = 'Vajalikud/teised osavõtjad';
$labels['prevslot'] = 'Eelnev aeg';
$labels['nextslot'] = 'Järgnev aeg';
$labels['noslotfound'] = 'Ei õnnestu leida vaba aega';
$labels['invitationsubject'] = 'Olete kutsutud "$title"';
$labels['invitationmailbody'] = "*\$title*\n\nWhen: \$date\n\nInvitees: \$attendees\n\nPlease find attached an iCalendar file with all the event details which you can import to your calendar application.";
$labels['invitationattendlinks'] = "In case your email client doesn't support iTip requests you can use the following link to either accept or decline this invitation:\n\$url";
$labels['eventupdatesubject'] = '"$title" has been updated';
$labels['eventupdatesubjectempty'] = 'An event that concerns you has been updated';
$labels['eventupdatemailbody'] = "*\$title*\n\nWhen: \$date\n\nInvitees: \$attendees\n\nPlease find attached an iCalendar file with the updated event details which you can import to your calendar application.";
$labels['eventcancelsubject'] = '"$title" has been canceled';
$labels['eventcancelmailbody'] = "*\$title*\n\nWhen: \$date\n\nInvitees: \$attendees\n\nThe event has been cancelled by \$organizer.\n\nPlease find attached an iCalendar file with the updated event details.";

// invitation handling
$labels['itipinvitation'] = 'Invitation to';
$labels['itipupdate'] = 'Update of';
$labels['itipcancellation'] = 'Cancelled:';
$labels['itipreply'] = 'Reply to';
$labels['itipaccepted'] = 'Accept';
$labels['itiptentative'] = 'Maybe';
$labels['itipdeclined'] = 'Decline';
$labels['itipsubjectaccepted'] = '"$title" has been accepted by $name';
$labels['itipsubjecttentative'] = '"$title" has been tentatively accepted by $name';
$labels['itipsubjectdeclined'] = '"$title" has been declined by $name';
$labels['itipmailbodyaccepted'] = "\$sender has accepted the invitation to the following event:\n\n*\$title*\n\nWhen: \$date\n\nInvitees: \$attendees";
$labels['itipmailbodytentative'] = "\$sender has tentatively accepted the invitation to the following event:\n\n*\$title*\n\nWhen: \$date\n\nInvitees: \$attendees";
$labels['itipmailbodydeclined'] = "\$sender has declined the invitation to the following event:\n\n*\$title*\n\nWhen: \$date\n\nInvitees: \$attendees";
$labels['itipdeclineevent'] = 'Do you want to decline your invitation to this event?';
$labels['importtocalendar'] = 'Salvesta minu kalendrisse';
$labels['removefromcalendar'] = 'Kustuta kalendrist';
$labels['updateattendeestatus'] = 'Värskenda osavõtja staatust';
$labels['acceptinvitation'] = 'Kas kutse vastu võtta?';
$labels['youhaveaccepted'] = 'Oled kutse vastu võtnud';
$labels['youhavetentative'] = 'Oled kutse tingimisi vastu võtnud';
$labels['youhavedeclined'] = 'Oled kutsest keeldunud';
$labels['notanattendee'] = 'Sa ei ole osavõtjate nimekirjas';
$labels['eventcancelled'] = 'Sündmus on tühistatud';
$labels['saveincalendar'] = 'salvesta';

// event dialog tabs
$labels['tabsummary'] = 'Kokkuvõte';
$labels['tabrecurrence'] = 'Kordumine';
$labels['tabattendees'] = 'Osavõtjad';
$labels['tabattachments'] = 'Manused';
$labels['tabsharing'] = 'Jagamine';

// messages
$labels['deleteventconfirm'] = 'Kas tõsti kustutada see sündmus?';
$labels['deletecalendarconfirm'] = 'Kas tõesti kustutada see kalender koos kõigi sündmustega?';
$labels['savingdata'] = 'Andmete salvestamine...';
$labels['errorsaving'] = 'Andmete salvestamine ebaõnnestus.';
$labels['operationfailed'] = 'Operatsioon nurjus.';
$labels['invalideventdates'] = 'Kuupäev on vigane! Kontrollige vormingut.';
$labels['invalidcalendarproperties'] = 'Vigane kalendri atribuut! Valige sobiv atribuut.';
$labels['searchnoresults'] = 'Sellest kalendrist ei leitud ühtki sündmust.';
$labels['successremoval'] = 'Sündmus on edukalt kustutatud.';
$labels['successrestore'] = 'Sündmus on edukalt taastatud.';
$labels['errornotifying'] = 'Teate saatmine osavõtjaile ebaõnnestus.';
$labels['errorimportingevent'] = 'Sündmuse import ebaõnnestus.';
$labels['newerversionexists'] = 'Uuem versioon sündmusest on juba olemas! Täitmine peatatud.';
$labels['nowritecalendarfound'] = 'Kirjutamiseks sobivat kalendrit ei leitud.';
$labels['importedsuccessfully'] = 'Sündmus on edukalt lisatud kalendrisse \'$calendar\'';
$labels['attendeupdateesuccess'] = 'Osavõtja staatus on uuendatud';
$labels['itipsendsuccess'] = 'Kutse on saadetud osavõtjaile.';
$labels['itipresponseerror'] = 'Vastuse saatmine kutsele ebaõnnestus.';
$labels['itipinvalidrequest'] = 'See kutse pole enam kehtiv.';
$labels['sentresponseto'] = 'Vastus kutsele on edukalt saadetud aadressile $mailto';
$labels['localchangeswarning'] = 'Muutuseid on näha ainult teie isiklikus kalendris.';
$labels['importsuccess'] = 'Edukalt imporditud $nr sündmust';
$labels['importnone'] = 'Ühtki imporditavat sündmust ei leitud';
$labels['importerror'] = 'Importimise käigus tekkis viga';
$labels['aclnorights'] = 'Ei ole selle kalendri administreerimisõigusi.';

// recurrence form
$labels['repeat'] = 'Korda';
$labels['frequency'] = 'Sagedus';
$labels['never'] = 'mitte kunagi';
$labels['daily'] = 'iga päev';
$labels['weekly'] = 'nädalati';
$labels['monthly'] = 'iga kuu';
$labels['yearly'] = 'iga aasta';
$labels['every'] = 'Iga';
$labels['days'] = 'päevad';
$labels['weeks'] = 'nädalad';
$labels['months'] = 'kuud';
$labels['years'] = 'aastad:';
$labels['bydays'] = 'On';
$labels['untildate'] = 'the';
$labels['each'] = 'Iga';
$labels['onevery'] = 'Igal';
$labels['onsamedate'] = 'samal kuupäeval';
$labels['forever'] = 'alati';
$labels['recurrencend'] = 'kuni';
$labels['forntimes'] = ' $nr korda';
$labels['first'] = 'esimesel';
$labels['second'] = 'teisel';
$labels['third'] = 'kolmandal';
$labels['fourth'] = 'neljandal';
$labels['last'] = 'viimasel';
$labels['dayofmonth'] = 'Kuupäev';

$labels['changeeventconfirm'] = 'Muuda sündmust';
$labels['removeeventconfirm'] = 'Kustuta sündmus';
$labels['changerecurringeventwarning'] = 'See on korduv sündmus. Kas muuta seda sündmust, seda ja kõiki järgnevaid, või salvestada uue sündmusena?';
$labels['removerecurringeventwarning'] = 'See on korduv sündmus. Kas kustudada see sündmus, see ja kõik järgnevad sündmused?';
$labels['currentevent'] = 'Praegune';
$labels['futurevents'] = 'Tulevikusündmused';
$labels['allevents'] = 'Kõik sündmused';
$labels['saveasnew'] = 'Salvesta uuena';

?>
