<?php

$labels = array();

// preferences
$labels['default_view'] = 'Вид по умолчанию';
$labels['time_format'] = 'Формат времени';
$labels['timeslots'] = 'Промежутков в часу';
$labels['first_day'] = 'Первый день недели';
$labels['first_hour'] = 'Показывать начиная с';
$labels['workinghours'] = 'Рабочие часы';
$labels['add_category'] = 'Добавить категорию';
$labels['remove_category'] = 'Удалить категорию';
$labels['defaultcalendar'] = 'Создавать новое событие в';
$labels['eventcoloring'] = 'Цвет события';
$labels['coloringmode0'] = 'Согласно цвета календаря';
$labels['coloringmode1'] = 'Согласно цвета категории';
$labels['coloringmode2'] = 'Цвет календаря для рамки, цвет категории для фона';
$labels['coloringmode3'] = 'Цвет категории для рамки, цвет календаря для фона';

// calendar
$labels['calendar'] = 'Календарь';
$labels['calendars'] = 'Календари';
$labels['category'] = 'Категория';
$labels['categories'] = 'Категории';
$labels['createcalendar'] = 'Создать новый календарь';
$labels['editcalendar'] = 'Редактировать свойства календаря';
$labels['name'] = 'Имя';
$labels['color'] = 'Цвет';
$labels['day'] = 'День';
$labels['week'] = 'Неделя';
$labels['month'] = 'Месяц';
$labels['agenda'] = 'Список';
$labels['new'] = 'Новый';
$labels['new_event'] = 'Новое событие';
$labels['edit_event'] = 'Изменить событие';
$labels['edit'] = 'Редактировать';
$labels['save'] = 'Сохранить';
$labels['remove'] = 'Удалить';
$labels['cancel'] = 'Отмена';
$labels['select'] = 'Выбрать';
$labels['print'] = 'Распечатать';
$labels['printtitle'] = 'Распечатать календарь';
$labels['title'] = 'Сводка';
$labels['description'] = 'Описание';
$labels['all-day'] = 'весь день';
$labels['export'] = 'Экспорт';
$labels['exporttitle'] = 'Экспорт в iCalendar';
$labels['location'] = 'Место';
$labels['date'] = 'Дата';
$labels['start'] = 'Начало';
$labels['end'] = 'Конец';
$labels['selectdate'] = 'Выберите дату';
$labels['freebusy'] = 'Показать как';
$labels['free'] = 'Свободен';
$labels['busy'] = 'Занят';
$labels['outofoffice'] = 'Вне офиса';
$labels['tentative'] = 'Неопределённо';
$labels['priority'] = 'Приоритет';
$labels['sensitivity'] = 'Секретность';
$labels['public'] = 'общедоступная';
$labels['private'] = 'личная';
$labels['confidential'] = 'конфиденциальная';
$labels['alarms'] = 'Напоминание';
$labels['generated'] = 'создан';
$labels['printdescriptions'] = 'Печатать описания';
$labels['parentcalendar'] = 'Вставить внутри';
$labels['searchearlierdates'] = '« Искать события раньше';
$labels['searchlaterdates'] = 'Искать события позже »';
$labels['andnmore'] = '$nr больше...';
$labels['togglerole'] = 'Кликните для переключения роли';
$labels['createfrommail'] = 'Сохранить как событие';
$labels['importevents'] = 'Импортировать события';
$labels['importrange'] = 'События начиная с';
$labels['onemonthback'] = '1 месяц назад';
$labels['nmonthsback'] = '$nr месяца(ев) назад';
$labels['showurl'] = 'Показать URL календаря';
$labels['showurldescription'] = 'Используйте следующий адрес для просмотра Вашего календаря из других приложений. Вы можете скопировать и вставить это в любое приложение которое поддерживает формат iCal.';

// agenda view
$labels['listrange'] = 'Диапазон:';
$labels['listsections'] = 'Разделить на:';
$labels['smartsections'] = 'Умные секции';
$labels['until'] = 'до';
$labels['today'] = 'Сегодня';
$labels['tomorrow'] = 'Завтра';
$labels['thisweek'] = 'Текущая неделя';
$labels['nextweek'] = 'Следующая неделя';
$labels['thismonth'] = 'Этот месяц';
$labels['nextmonth'] = 'Следующий месяц';
$labels['weekofyear'] = 'Неделя';
$labels['pastevents'] = 'Прошедшее';
$labels['futureevents'] = 'Будущее';

// alarm/reminder settings
$labels['showalarms'] = 'Показывать напоминания';
$labels['defaultalarmtype'] = 'Настройки напоминания по умолчанию';
$labels['defaultalarmoffset'] = 'Время напоминания по умолчанию';

// attendees
$labels['attendee'] = 'Участник';
$labels['role'] = 'Роль';
$labels['availability'] = 'Доступность';
$labels['confirmstate'] = 'Статус';
$labels['addattendee'] = 'Добавить участника';
$labels['roleorganizer'] = 'Организатор';
$labels['rolerequired'] = 'Обязательный';
$labels['roleoptional'] = 'Необязательный';
$labels['roleresource'] = 'Запасной';
$labels['availfree'] = 'Свободен';
$labels['availbusy'] = 'Занят';
$labels['availunknown'] = 'Неизвестно';
$labels['availtentative'] = 'Предварительно';
$labels['availoutofoffice'] = 'Вне офиса';
$labels['scheduletime'] = 'Найти доступность';
$labels['sendinvitations'] = 'Отправить приглашения';
$labels['sendnotifications'] = 'Уведомить участников об изменениях';
$labels['sendcancellation'] = 'Уведомить участников об отмене события';
$labels['onlyworkinghours'] = 'Найти доступность в мои рабочие часы';
$labels['reqallattendees'] = 'Необходимые/все участники';
$labels['prevslot'] = 'Предыдущее время';
$labels['nextslot'] = 'Следующее время';
$labels['noslotfound'] = 'Невозможно найти свободное время';
$labels['invitationsubject'] = 'Вы приглашены на "$title"';
$labels['invitationmailbody'] = "*\$title*\n\nКогда: \$date\n\nПриглашенные: \$attendees\n\nВо вложении вы найдёте файл iCalendar со всеми деталями события, который Вы можете импортировать в Вашу программу-ежедневник.";
$labels['invitationattendlinks'] = "В случае, если Ваш почтовый клиент не поддерживает запросы iTip, Вы можете использовать ссылку данную ниже, чтобы принять или отклонить это приглашение:\n\$url";
$labels['eventupdatesubject'] = '"$title" было обновлено';
$labels['eventupdatesubjectempty'] = 'Событие, которое касается Вас, было обновлено';
$labels['eventupdatemailbody'] = "*\$title*\n\nКогда: \$date\n\nПриглашенные: \$attendees\n\nВо вложении вы найдёте файл iCalendar со всеми изменениями в событии, который Вы можете импортировать в Вашу программу-ежедневник.";
$labels['eventcancelsubject'] = '"$title" было отменено';
$labels['eventcancelmailbody'] = "*\$title*\n\nКогда: \$date\n\nПриглашенные: \$attendees\n\nЭто событие отменено \$organizer.\n\nВо вложении вы найдёте файл iCalendar со всеми изменениями в событии.";

// invitation handling
$labels['itipinvitation'] = 'Приглашение на';
$labels['itipupdate'] = 'Обновление';
$labels['itipcancellation'] = 'Отменённый:';
$labels['itipreply'] = 'Ответить';
$labels['itipaccepted'] = 'Принять';
$labels['itiptentative'] = 'Может быть';
$labels['itipdeclined'] = 'Отклонить';
$labels['itipsubjectaccepted'] = '"$title" принято $name';
$labels['itipsubjecttentative'] = '"$title" предварительно принято $name';
$labels['itipsubjectdeclined'] = '"$title" отклонено $name';
$labels['itipmailbodyaccepted'] = "\$sender принял(а) приглашение на следующее событие:\n\n*\$title*\n\nКогда: \$date\n\nПриглашенные: \$attendees";
$labels['itipmailbodytentative'] = "\$sender предварительно принял(а) приглашение на следующее событие:\n\n*\$title*\n\nКогда: \$date\n\nПриглашенные: \$attendees";
$labels['itipmailbodydeclined'] = "\$sender отклонил(а) приглашение на следующее событие:\n\n*\$title*\n\nКогда: \$date\n\nПриглашенные: \$attendees";
$labels['itipdeclineevent'] = 'Вы хотите отклонить приглашение на это событие?';
$labels['importtocalendar'] = 'Сохранить в мой календарь';
$labels['removefromcalendar'] = 'Удалить из моего календаря';
$labels['updateattendeestatus'] = 'Обновить статус участника';
$labels['acceptinvitation'] = 'Вы принимаете это приглашение?';
$labels['youhaveaccepted'] = 'Вы приняли это приглашение';
$labels['youhavetentative'] = 'Вы предварительно приняли это приглашение';
$labels['youhavedeclined'] = 'Вы отклонили это приглашение';
$labels['notanattendee'] = 'Вы не в списке участников этого события';
$labels['eventcancelled'] = 'Это событие отменено';
$labels['saveincalendar'] = 'сохранить в';

// event dialog tabs
$labels['tabsummary'] = 'Сводка';
$labels['tabrecurrence'] = 'Повторение';
$labels['tabattendees'] = 'Участники';
$labels['tabattachments'] = 'Вложения';
$labels['tabsharing'] = 'Совместное использование';

// messages
$labels['deleteventconfirm'] = 'Вы действительно хотите удалить это событие?';
$labels['deletecalendarconfirm'] = 'Вы действительно хотите удалить этот календарь со всеми его событиями?';
$labels['savingdata'] = 'Сохранение данных...';
$labels['errorsaving'] = 'Ошибка сохранения изменений.';
$labels['operationfailed'] = 'Не удалось выполнить запрошенную операцию.';
$labels['invalideventdates'] = 'Неверная дата! Пожалуйста проверьте данные.';
$labels['invalidcalendarproperties'] = 'Неверные свойства календаря! Пожалуйста введите допустимые данные.';
$labels['searchnoresults'] = 'Событие не найдено в выбранных календарях.';
$labels['successremoval'] = 'Событие успешно удалено.';
$labels['successrestore'] = 'Событие успешно восстановлено.';
$labels['errornotifying'] = 'Не удалось отправить уведомления участникам событий';
$labels['errorimportingevent'] = 'Не удалось импортировать событие';
$labels['newerversionexists'] = 'Обновлённая версия этого события уже существует! Отменено.';
$labels['nowritecalendarfound'] = 'Не найден календарь для записи этого события';
$labels['importedsuccessfully'] = 'Событие успешно добавлено в \'$calendar\'';
$labels['attendeupdateesuccess'] = 'Успешно обновлен статус участника';
$labels['itipsendsuccess'] = 'Приглашания отправлены участникам.';
$labels['itipresponseerror'] = 'Не удалось послать ответ на это приглашение';
$labels['itipinvalidrequest'] = 'Это приглашение больше не действительно';
$labels['sentresponseto'] = 'Успешно отправлен ответ на приглашение на $mailto';
$labels['localchangeswarning'] = 'Вы собираетесь внести изменения, которые будут отражены только на Вашем личном календаре';
$labels['importsuccess'] = 'Успешно импортировано $nr событий';
$labels['importnone'] = 'Не найдено событий для импорта';
$labels['importerror'] = 'Ошибка при импорте';
$labels['aclnorights'] = 'Вы не имеете прав администратора для этого календаря.';

// recurrence form
$labels['repeat'] = 'Повторить';
$labels['frequency'] = 'Повторить';
$labels['never'] = 'никогда';
$labels['daily'] = 'ежедневно';
$labels['weekly'] = 'еженедельно';
$labels['monthly'] = 'ежемесячно';
$labels['yearly'] = 'ежегодно';
$labels['every'] = 'Каждый(ую)';
$labels['days'] = 'день';
$labels['weeks'] = 'неделю';
$labels['months'] = 'месяц';
$labels['years'] = 'год в:';
$labels['bydays'] = 'В';
$labels['untildate'] = 'до';
$labels['each'] = 'Каждого';
$labels['onevery'] = 'В';
$labels['onsamedate'] = 'В ту же самую дату';
$labels['forever'] = 'всегда';
$labels['recurrencend'] = 'Повторять';
$labels['forntimes'] = '$nr раз(а)';
$labels['first'] = 'первый(ую)';
$labels['second'] = 'вторый(ую)';
$labels['third'] = 'третий(ую)';
$labels['fourth'] = 'четвертый(ую)';
$labels['last'] = 'последний(ую)';
$labels['dayofmonth'] = 'День месяца';

$labels['changeeventconfirm'] = 'Изменить событие';
$labels['removeeventconfirm'] = 'Удалить событие';
$labels['changerecurringeventwarning'] = 'Это - повторяющееся событие. Хотели бы Вы редактировать только текущее событие, это и все будущие повторения, все события или сохранять его как новое событие?';
$labels['removerecurringeventwarning'] = 'Это - повторяющееся событие. Хотели бы Вы удалить только текущее событие, это и все будущие события или все эти события?';
$labels['currentevent'] = 'Текущее';
$labels['futurevents'] = 'Будущие';
$labels['allevents'] = 'Все';
$labels['saveasnew'] = 'Сохранить как новое';

?>
