<?php
/**
 * Localizations for Kolab Calendar plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/calendar/
 */
$labels['aftermoveto'] = 'Presunúť do...';
$labels['calendar'] = 'Kalendár';
$labels['calendars'] = 'Kalendáre';
$labels['category'] = 'Kategória';
$labels['categories'] = 'Kategórie';
$labels['createcalendar'] = 'Vytvoriť nový kalendár';
$labels['editcalendar'] = 'Upraviť nastavenie kalendára';
$labels['name'] = 'Meno';
$labels['color'] = 'Farba';
$labels['day'] = 'Deň';
$labels['week'] = 'Týždeň';
$labels['month'] = 'Mesiac';
$labels['agenda'] = 'Agenda';
$labels['new'] = 'Nový';
$labels['new_event'] = 'Nová udalosť';
$labels['edit_event'] = 'Upraviť udalosť';
$labels['edit'] = 'Upraviť';
$labels['save'] = 'Uložiť';
$labels['weekofyear'] = 'Týždeň';
?>
