<?php
/* Author: Thom Heemstra */

$labels = array();
$labels['buttonjunk'] = 'Markeer als spam';
$labels['markasjunk'] = 'Spam';
$labels['buttonnotjunk'] = 'Dit bericht is geen spam';
$labels['markasnotjunk'] = 'Geen spam';
$labels['notjunk'] = 'Geen spam';

$messages = array();
$messages['reportedasjunk'] = 'Dit bericht is gemarkeerd als spam';
$messages['reportedasnotjunk'] = 'Dit bericht is niet meer gemarkeerd als spam';

?>
