<?php
/* Author: Hans Spaans, Thom Heemstra */

$labels = array();
$labels['buttonjunk'] = 'Markeer als spam';
$labels['markasjunk'] = 'Is spam';
$labels['buttonnotjunk'] = 'Dit bericht is geen spam';
$labels['markasnotjunk'] = 'Geen spam';

$messages = array();
$messages['reportedasjunk'] = 'Bericht is gemarkeerd als spam';
$messages['reportedasnotjunk'] = 'Bericht gemarkeerd als geen spam';

?>
