<?php

$labels = array();
$labels['verifiedsender'] = 'Geldige digitale handtekening, afkomstig van het domein van de afzender. Gecontroleerd door ';
$labels['invalidsignature'] = 'Digitale handtekening is ongeldig! Gecontroleerd door ';
$labels['nosignature'] = 'Geen digitale handtekening';
$labels['thirdpartysig'] = 'Geen digitale handtekening afkomstig van het domein van de afzender. Er is wel een digitale handtekening aanwezig van een ander domein. Gecontroleerd door ';

?>
