<?php
/**
 * Localizations for the Kolab calendaring utilities plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libcalendaring/
 */
$labels['until'] = 'fins';
$labels['at'] = 'a';
$labels['alarmemailoption'] = 'Email';
$labels['frequency'] = 'Repeteix';
$labels['recurrencend'] = 'fins';
$labels['statusorganizer'] = 'Organitzador';
$labels['statustentative'] = 'Provisional';
$labels['statusneeds-action'] = 'Necessita una acció';
$labels['statusunknown'] = 'Desconegut';
$labels['statuscompleted'] = 'Completat';
$labels['statusin-process'] = 'En procés';
$labels['savingdata'] = 'S\'estan desant les dades...';
