<?php

$labels = array();

$labels['alarmemail'] = 'Poslat e-mail';
$labels['alarmdisplay'] = 'Zobrazit zprávu';
$labels['alarmdisplayoption'] = 'Zpráva';
$labels['alarmemailoption'] = 'E-mail';
$labels['alarmat'] = '$datetime';
$labels['trigger@'] = 'dne';
$labels['trigger-M'] = 'minut před';
$labels['trigger-H'] = 'hodin před';
$labels['trigger-D'] = 'dnů před';
$labels['trigger+M'] = 'minut po';
$labels['trigger+H'] = 'hodin po';
$labels['trigger+D'] = 'dnů po';
$labels['addalarm'] = 'přidat upozornění';

$labels['alarmtitle'] = 'Blížící se události';
$labels['dismissall'] = 'Zrušit vše';
$labels['dismiss'] = 'Zrušit';
$labels['snooze'] = 'Odložit';
$labels['repeatinmin'] = 'Zopakovat za $min minut';
$labels['repeatinhr'] = 'Zopakovat za 1 hodinu';
$labels['repeatinhrs'] = 'Zopakovat za $hrs hodin';
$labels['repeattomorrow'] = 'Zopakovat zítra';
$labels['repeatinweek'] = 'Zopakovat za týden';

$labels['showmore'] = 'Ukázat víc...';

