<?php
/**
 * Localizations for the Kolab calendaring utilities plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libcalendaring/
 */
$labels['alarmemailoption'] = 'E-post';
$labels['statusorganizer'] = 'Organizer';
$labels['statustentative'] = 'Tentative';
$labels['statusneeds-action'] = 'Needs action';
$labels['statusunknown'] = 'Unknown';
$labels['statuscompleted'] = 'Completed';
$labels['statusin-process'] = 'In process';
