<?php
/**
 * Localizations for the Kolab calendaring utilities plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libcalendaring/
 */
$labels['until'] = 'kunnes';
$labels['alarmemail'] = 'Lähetä sähköposti';
$labels['alarmdisplay'] = 'Näytä viesti';
$labels['alarmaudio'] = 'Toista ääni';
$labels['alarmdisplayoption'] = 'Viesti';
$labels['alarmemailoption'] = 'Sähköposti';
$labels['alarmaudiooption'] = 'Ääni';
$labels['trigger-M'] = 'minuuttia ennen';
$labels['trigger-H'] = 'tuntia ennen';
$labels['trigger-D'] = 'päivää ennen';
$labels['alarmtitle'] = 'Tulevat tapahtumat';
$labels['dismissall'] = 'Hylkää kaikki';
$labels['dismiss'] = 'Hylkää';
$labels['snooze'] = 'Torkuta';
$labels['repeatinmin'] = 'Toista $min minuutin päästä';
$labels['repeatinhr'] = 'Toista 1 tunnin päästä';
$labels['repeatinhrs'] = 'Toista $hrs tunnin päästä';
$labels['repeattomorrow'] = 'Toista huomenna';
$labels['repeatinweek'] = 'Toista viikon päästä';
$labels['showmore'] = 'Näytä lisää...';
$labels['frequency'] = 'Toista';
$labels['never'] = 'ei koskaan';
$labels['daily'] = 'päivittäin';
$labels['weekly'] = 'viikottain';
$labels['monthly'] = 'kuukausittain';
$labels['yearly'] = 'vuosittain';
$labels['forever'] = 'ikuisesti';
$labels['recurrencend'] = 'kunnes';
$labels['itipcancellation'] = 'Peruttu:';
$labels['itipaccepted'] = 'Hyväksy';
$labels['itiptentative'] = 'Ehkä';
$labels['itipdeclined'] = 'Kieltäydy';
$labels['itipdelegated'] = 'Edustaja';
$labels['itipcomment'] = 'Oma vastaus';
$labels['itipeditresponse'] = 'Kirjoita vastausteksti';
$labels['itipsendercomment'] = 'Lähettäjän kommentti:';
$labels['itipsuppressreply'] = 'Älä lähetä vastausta';
$labels['itipsubjectaccepted'] = '$name on hyväksynyt tapahtuman "$title"';
$labels['itipsubjecttentative'] = '$name on alustavasti hyväkstynyt tapahtuman "$title"';
$labels['itipsubjectdeclined'] = '$name on kieltäytynyt osallistumasta tapahtumaan "$title"';
$labels['acceptinvitation'] = 'Hyväksytkö tämän kutsun?';
$labels['youhaveaccepted'] = 'Olet hyväksynyt tämän kutsun';
$labels['youhavetentative'] = 'Olet hyväksynyt tämän kutsun alustavasti';
$labels['youhavedeclined'] = 'Olet kieltäytynyt tästä kutsusta';
$labels['importtocalendar'] = 'Tallenna omaan kalenteriin';
$labels['removefromcalendar'] = 'Poista omasta kalenterista';
$labels['savingdata'] = 'Tallennetaan tietoja...';
