<?php

$labels = array();

$labels['alarmemail'] = 'Envoyer un email';
$labels['alarmdisplay'] = 'Voir le message';
$labels['alarmdisplayoption'] = 'Message';
$labels['alarmemailoption'] = 'Email';
$labels['alarmat'] = 'à $datetime';
$labels['trigger@'] = 'à la date';
$labels['trigger-M'] = 'minutes avant';
$labels['trigger-H'] = 'heures avant';
$labels['trigger-D'] = 'jours avant';
$labels['trigger+M'] = 'minutes après';
$labels['trigger+H'] = 'heures après';
$labels['trigger+D'] = 'jours après';
$labels['addalarm'] = 'ajouter alarme';

$labels['alarmtitle'] = 'Evénements à venir';
$labels['dismissall'] = 'Tout supprimer';
$labels['dismiss'] = 'Abandonner';
$labels['snooze'] = 'En pause';
$labels['repeatinmin'] = 'Répéter dans $min minutes';
$labels['repeatinhr'] = 'Répéter dans 1 heure';
$labels['repeatinhrs'] = 'Répéter dans $hrs heures';
$labels['repeattomorrow'] = 'Répéter demain';
$labels['repeatinweek'] = 'Répéter dans une semaine';

$labels['showmore'] = 'Afficher plus...';

