<?php
/**
 * Localizations for the Kolab calendaring utilities plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libcalendaring/
 */
$labels['until'] = 'until';
$labels['frequency'] = 'Repeat';
$labels['recurrencend'] = 'until';
$labels['statusorganizer'] = 'Organizer';
$labels['statustentative'] = 'Tentative';
$labels['statusunknown'] = 'Unknown';
$labels['savingdata'] = 'Saving data...';
