<?php
/**
 * Localizations for the Kolab calendaring utilities plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libcalendaring/
 */
$labels['until'] = '까지';
$labels['frequency'] = '반복';
$labels['recurrencend'] = '까지';
$labels['statusorganizer'] = '주최자';
$labels['statustentative'] = '임시';
$labels['statusunknown'] = '알 수 없는';
$labels['savingdata'] = '자료 저장중...';
