<?php
/**
 * Localizations for the Kolab calendaring utilities plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libcalendaring/
 */
$labels['until'] = 'dopóki';
$labels['frequency'] = 'Powtórz';
$labels['recurrencend'] = 'dopóki';
$labels['statusorganizer'] = 'Organizator';
$labels['statustentative'] = 'Niepewny';
$labels['statusunknown'] = 'Nieznany';
$labels['savingdata'] = 'Zapisuję dane...';
