<?php

$labels = array();

$labels['alarmemail'] = 'Wyślij pocztę';
$labels['alarmdisplay'] = 'Pokaż wiadomość';
$labels['alarmdisplayoption'] = 'Wiadomość';
$labels['alarmemailoption'] = 'Poczta';
$labels['alarmat'] = 'o $datetime';
$labels['trigger@'] = 'w dniu';
$labels['trigger-M'] = 'minuty przed';
$labels['trigger-H'] = 'godziny przed';
$labels['trigger-D'] = 'dni przed';
$labels['trigger+M'] = 'minut po';
$labels['trigger+H'] = 'godziny po';
$labels['trigger+D'] = 'dni po';
$labels['addalarm'] = 'dodaj alarm';

$labels['alarmtitle'] = 'Nadchodzące zdarzenia';
$labels['dismissall'] = 'Odrzuć wszystkie';
$labels['dismiss'] = 'Odrzuć';
$labels['snooze'] = 'Odłóż';
$labels['repeatinmin'] = 'Powtórz po $min minutach';
$labels['repeatinhr'] = 'Powtórz po godzinie';
$labels['repeatinhrs'] = 'Powtórz po $hrs godzinach';
$labels['repeattomorrow'] = 'Powtórz jutro';
$labels['repeatinweek'] = 'Powtórz za tydzień';

