<?php

$labels = array();

$labels['alarmemail'] = 'Послать e-mail';
$labels['alarmdisplay'] = 'Показать сообщение';
$labels['alarmdisplayoption'] = 'Сообщение';
$labels['alarmemailoption'] = 'Email';
$labels['alarmat'] = 'на $datetime';
$labels['trigger@'] = 'на дату';
$labels['trigger-M'] = 'минут до';
$labels['trigger-H'] = 'часов до';
$labels['trigger-D'] = 'дней до';
$labels['trigger+M'] = 'минут после';
$labels['trigger+H'] = 'часов после';
$labels['trigger+D'] = 'дней после';
$labels['addalarm'] = 'добавить уведомление';

$labels['alarmtitle'] = 'Предстоящие события';
$labels['dismissall'] = 'Отменить все';
$labels['dismiss'] = 'Отменить';
$labels['snooze'] = 'Отложить';
$labels['repeatinmin'] = 'Повторить через $min minutes';
$labels['repeatinhr'] = 'Повторить через 1 час';
$labels['repeatinhrs'] = 'Повторить через $hrs часов';
$labels['repeattomorrow'] = 'Повторить завтра';
$labels['repeatinweek'] = 'Повторить через неделю';

$labels['showmore'] = 'Показать больше...';
