<?php
/**
 * Localizations for the Kolab calendaring utilities plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libcalendaring/
 */
$labels['until'] = 'do';
$labels['at'] = 'ob';
$labels['alarmemailoption'] = 'Email';
$labels['frequency'] = 'Ponovi';
$labels['recurrencend'] = 'do';
$labels['statusorganizer'] = 'Organizator';
$labels['statustentative'] = 'Pogojno';
$labels['statusneeds-action'] = 'Potrebuje pozornost';
$labels['statusunknown'] = 'Neznano';
$labels['statuscompleted'] = 'Opravljeno';
$labels['statusin-process'] = 'V procesu';
$labels['itipdelegated'] = 'Sodelujoč';
$labels['savingdata'] = 'Shranjujem...';
