<?php
/**
 * Localizations for the Kolab calendaring utilities plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libcalendaring/
 */
$labels['until'] = 'tills';
$labels['frequency'] = 'Upprepa';
$labels['recurrencend'] = 'tills';
$labels['statusorganizer'] = 'Organisatör';
$labels['statustentative'] = 'Preliminärt';
$labels['statusunknown'] = 'Okänd';
$labels['savingdata'] = 'Sparar data ...';
