<?php
/**
 * Localizations for the Kolab calendaring utilities plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libcalendaring/
 */
$labels['until'] = '直到';
$labels['at'] = '在';
$labels['alarmemail'] = '发送邮件';
$labels['alarmdisplay'] = '显示消息';
$labels['alarmaudio'] = '播放声音';
$labels['alarmdisplayoption'] = '消息';
$labels['alarmemailoption'] = '邮件';
$labels['alarmaudiooption'] = '声音';
$labels['alarmat'] = '在 $datetime';
$labels['trigger-M'] = '分钟以前';
$labels['trigger-H'] = '小时以前';
$labels['trigger-D'] = '天以前';
$labels['trigger+M'] = '分钟以后';
$labels['trigger+H'] = '小时以后';
$labels['trigger+D'] = '天以后';
$labels['triggerend-M'] = '还有xxx分钟结束 # xxx was supposed to be the number before "minutes before end"';
$labels['frequency'] = '循环';
$labels['recurrencend'] = '直到';
$labels['statusorganizer'] = '组织者';
$labels['statustentative'] = '临时';
$labels['statusunknown'] = '未知';
$labels['savingdata'] = '保存数据...';
