<?php
/*
+-----------------------------------------------------------------------+
| ./plugins/pop3fetcher/localization/en_US.inc |
| Language file of roundcube-pop3fetcher plugin |
| Copyright (C) 2010-2013, Paolo 'morepaolo' Moretti |
| Licensed under the GNU GPL |
| |
+-----------------------------------------------------------------------+
| Author: Paolo Moretti <morepaolo@gmail.com> |
+-----------------------------------------------------------------------+
*/
$labels = array();
$labels['other_accounts'] = 'Други акаунти';
$labels['editaccount'] = 'Редактирай акаунт';
$labels['addaccount'] = 'Добави акаунт';
$labels['account_email'] = 'Имейл';
$labels['account_username'] = 'Потребител';
$labels['account_password'] = 'Парола';
$labels['account_serveraddress'] = 'Адрес на сървъра';
$labels['account_serverport'] = 'Порт на сървъра';
$labels['account_usessl'] = 'Използвай SSL';
$labels['account_leaveacopy'] = 'Остави копие на сървъра при изтегляне';
$labels['account_unableconnect'] = 'Неуспешно свързване към сървър';
$labels['account_provider'] = 'Услуга';
$labels['test_connection_on_save'] = 'Тествай връзката при запис';
$labels['account_default_folder'] = 'Default Folder';
$labels['pop3fetcher_current_version'] = 'CURRENT VERSION: ';
$labels['pop3fetcher_latest_version'] = 'Latest version is: ';
$labels['pop3fetcher_updated'] = 'Pop3fetcher is updated to the latest version';
$labels['pop3fetcher_outdated'] = "There's an update available for Pop3fetcher.<br />Download it from ";
$labels['account_import_old_messages'] = 'Import old messages';
/* FROM NOW ON: CHECK */
$labels['pluginname'] = 'Remote IMAP Accounts';
$labels['plugindescription'] = 'Allows a user to access messages stored in any remote folder as if it were a local folder.';
$labels['account_dn'] = 'Account Name';
$labels['account_id'] = 'Login ID';
$labels['account_pw'] = 'Password';
$labels['account_pw_conf'] = 'Confirm Password';
$labels['account_provider'] = 'Provider';
$labels['add'] = 'Add';
$labels['back'] = 'Abort';
$labels['submit'] = 'Submit';
$labels['archivefolder'] = 'Archive';
$labels['remotefolders'] = 'Special Folders';
$labels['description'] = 'Manage additional IMAP Accounts.';
$labels['dnempty'] = 'Please enter a name for this account';
$labels['userempty'] = 'Please enter account login ID';
$labels['passwordempty'] = 'Please enter password';
$labels['passwordnotmatch'] = 'Password does not match';
$labels['hostempty'] = 'Please enter host url (f.e. ssl://imap.gmail.com:993)';
$labels['accountexists'] = 'This account already exists. You have been redirected to edit mode.';
$labels['connectionfailed'] = 'Failed to establish connection to remote host.';
?>
