<?php

/*
+-----------------------------------------------------------------------+
| ./plugins/pop3fetcher/localization/cz_CZ.inc                          | 
| Language file of roundcube-pop3fetcher plugin				| 
| Copyright (C) 2010-2013, Paolo 'morepaolo' Moretti			|	
| Licensed under the GNU GPL						|
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Daniel Bilik <daniel.bilik@neosystem.cz>			|
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['other_accounts'] = 'Další účty';
$labels['editaccount'] = 'Upravit účet';
$labels['addaccount'] = 'Přidat účet';
$labels['account_email'] = 'Email';
$labels['account_username'] = 'Přihlašovací jméno';
$labels['account_password'] = 'Heslo';
$labels['account_serveraddress'] = 'Adresa serveru';
$labels['account_serverport'] = 'Port serveru';
$labels['account_usessl'] = 'Používat SSL';
$labels['account_leaveacopy'] = 'Nechávat kopii zprávy na serveru';
$labels['account_unableconnect'] = "Spojení na vzdálený server selhalo";
$labels['account_provider'] = 'Poskytovatel';
$labels['test_connection_on_save'] = 'Ověřit spojení při uložení';
$labels['account_default_folder'] = 'Cílová složka';
$labels['pop3fetcher_current_version'] = 'Používaná verze: ';
$labels['pop3fetcher_latest_version'] = 'Aktuální verze: ';
$labels['pop3fetcher_updated'] = 'Pop3fetcher je aktuální';
$labels['pop3fetcher_outdated'] = "Je k dispozici aktualizace pro Pop3fetcher.<br />Ke stažení z ";
$labels['account_import_old_messages'] = 'Import old messages';


/* FROM NOW ON: CHECK */
$labels['pluginname'] = 'Vzdálené IMAP účty';
$labels['plugindescription'] = 'Přístup ke zprávám v jakékoliv vzdálené složce, jako by to byla složka místní.';
$labels['account_dn'] = 'Název účtu';
$labels['account_id'] = 'Přihlašovací jméno';
$labels['account_pw'] = 'Heslo';
$labels['account_pw_conf'] = 'Potvrzení hesla';
$labels['account_provider'] = 'Poskytovatel';
$labels['add'] = 'Přidat';
$labels['back'] = 'Zrušit';
$labels['submit'] = 'Uložit';
$labels['archivefolder'] = 'Archív';
$labels['remotefolders'] = 'Speciální složky';
$labels['description'] = 'Spravovat další IMAP účty.';
$labels['dnempty'] = 'Prosím zadejte název tohoto účtu';
$labels['userempty'] = 'Prosím zadejte přihlašovací jméno';
$labels['passwordempty'] = 'Prosím zadejte heslo';
$labels['passwordnotmatch'] = 'Hesla nesouhlasí';
$labels['hostempty'] = 'Prosím zadejte URL serveru (např. ssl://imap.gmail.com:993)';
$labels['accountexists'] = 'Tento účet již existuje. Došlo k přesměrování do editačního režimu.';
$labels['connectionfailed'] = 'Spojení na vzdálený server selhalo.';

?>
