<?php

$labels = array();
$labels['other_accounts'] = 'Andre konti';
$labels['editaccount'] = 'Rediger konto';
$labels['addaccount'] = 'Tilføj POP3-konto';
$labels['account_email'] = 'E-mail';
$labels['account_username'] = 'Brugernavn';
$labels['account_password'] = 'Adgangskode';
$labels['account_serveraddress'] = 'Serveradresse';
$labels['account_serverport'] = 'Serverport';
$labels['account_usessl'] = 'Brug SSL';
$labels['account_leaveacopy'] = 'Efterlad en kopi af meddelelsen på serveren ';
$labels['account_unableconnect'] = "Kan ikke forbinde med adresse";
$labels['account_provider'] = 'Udbyder';
$labels['test_connection_on_save'] = 'Test forbindelse ved lagring';
$labels['account_default_folder'] = 'Standardmappe';
$labels['pop3fetcher_current_version'] = 'AKTUEL VERSION: ';
$labels['pop3fetcher_latest_version'] = 'Nyeste version er:';
$labels['pop3fetcher_updated'] = 'Pop3fetcher er opdateret til den nyeste version';
$labels['pop3fetcher_outdated'] = "Der er en opdatering til rådighed for Pop3fetcher.<br />Hent den fra ";
$labels['account_import_old_messages'] = 'Importer gamle beskeder';


$labels['pluginname'] = 'Eksterne IMAP-konti';
$labels['plugindescription'] = 'Giver en bruger mulighed for at få adgang til meddelelser, der er gemt i enhver ekstern mappe, som om det var en lokal mappe.';
$labels['account_dn'] = 'Kontonavn';
$labels['account_id'] = 'Brugernavn';
$labels['account_pw'] = 'Adgangskode';
$labels['account_pw_conf'] = 'Bekræft adgangskode';
$labels['account_provider'] = 'Udbyder';
$labels['add'] = 'Tilføj';
$labels['back'] = 'Afbryd';
$labels['submit'] = 'Send';
$labels['archivefolder'] = 'Arkiv';
$labels['remotefolders'] = 'Særlige mapper';
$labels['description'] = 'Administrer yderligere IMAP-konti.';
$labels['dnempty'] = 'Indtast et navn for denne konto';
$labels['userempty'] = 'Indtast brugernavn for konto';
$labels['passwordempty'] = 'Indtast adgangskode';
$labels['passwordnotmatch'] = 'Adgangskode matcher ikke';
$labels['hostempty'] = 'Indtast URL-adresse til webstedsvært (fe ssl:/ / imap.gmail.com: 993)';
$labels['accountexists'] = 'Denne konto findes allerede. Du er blevet omdirigeret til at redigeringsfunktionen'.;
$labels['connectionfailed'] = 'Kunne ikke oprette forbindelse med fjernvært.';
?>
