<?php

$labels = array();
$labels['other_accounts'] = 'Otras Cuentas';
$labels['editaccount'] = 'Editar cuenta';
$labels['addaccount'] = 'Agregar cuenta POP3';
$labels['account_email'] = 'Correo electrónico';
$labels['account_username'] = 'Nombre de usuario';
$labels['account_password'] = 'Contraseña';
$labels['account_serveraddress'] = 'Dirección del servidor';
$labels['account_serverport'] = 'Puerto del servidor';
$labels['account_usessl'] = 'Usar SSL';
$labels['account_leaveacopy'] = 'Dejar una copia del mensaje en el servidor';
$labels['account_unableconnect'] = "No se puede conectar a la dirección";
$labels['account_provider'] = 'Proveedor';
$labels['test_connection_on_save'] = 'Probar conexión al guardar';
$labels['account_default_folder'] = 'Carpeta predeterminada';
$labels['pop3fetcher_current_version'] = 'VERSIÓN ACTUAL:';
$labels['pop3fetcher_latest_version'] = 'La versión más reciente es:';
$labels['pop3fetcher_updated'] = 'Pop3fetcher se ha actualizado a la versión más reciente';
$labels['pop3fetcher_outdated'] = "Hay una actualización disponible para Pop3fetcher.<br />Puede descargarla de ";
$labels['account_import_old_messages'] = 'Importar mensajes antiguos';


$labels['pluginname'] = 'Cuentas IMAP remotas';
$labels['plugindescription'] = 'Le permite a un usuario acceder a mensajes almacenados en cualquier carpeta remota como si fuera una carpeta local.';
$labels['account_dn'] = 'Nombre de cuenta';
$labels['account_id'] = 'ID de inicio de sesión';
$labels['account_pw'] = 'Contraseña';
$labels['account_pw_conf'] = 'Confirme la nueva contraseña';
$labels['account_provider'] = 'Proveedor';
$labels['add'] = 'Añadir';
$labels['back'] = 'Cancelar';
$labels['submit'] = 'Enviar';
$labels['archivefolder'] = 'Archivar';
$labels['remotefolders'] = 'Carpetas especiales';
$labels['description'] = 'Administrar cuentas IMAP adicionales.';
$labels['dnempty'] = 'Asígnele un nombre a esta cuenta';
$labels['userempty'] = 'Ingrese la ID de inicio de sesión en esta cuenta';
$labels['passwordempty'] = 'Ingrese la contraseña';
$labels['passwordnotmatch'] = 'La contraseña no coincide';
$labels['hostempty'] = 'Ingrese la dirección url del host (p. ej., ssl://imap.gmail.com:993)';
$labels['accountexists'] = 'Esta cuenta ya existe. Se lo ha redirigido al modo de edición.';
$labels['connectionfailed'] = 'No se pudo establecer conexión con el host remoto.';
?>
