<?php

/*
+-----------------------------------------------------------------------+
| ./plugins/pop3fetcher/localization/en_GB.inc                          | 
| Language file of roundcube-pop3fetcher plugin							| 
| Copyright (C) 2010-2013, Paolo 'morepaolo' Moretti					|	
| Licensed under the GNU GPL											|
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Paolo Moretti <morepaolo@gmail.com>            	            |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['other_accounts'] = 'Autres Comptes';
$labels['editaccount'] = 'Editer le compte';
$labels['addaccount'] = 'Ajouter un compte';
$labels['account_email'] = 'Email';
$labels['account_username'] = "Nom d'utilisateur";
$labels['account_password'] = 'Mot de passe';
$labels['account_serveraddress'] = 'Adresse du Serveur';
$labels['account_serverport'] = 'Port';
$labels['account_usessl'] = 'Utiliser SSL';
$labels['account_leaveacopy'] = 'Laisser une copie du message sur le serveur';
$labels['account_unableconnect'] = "Impossible de se connecter à l'adresse";
$labels['account_provider'] = 'Fournisseur';
$labels['test_connection_on_save'] = 'Tester la connexion avant de sauvegarder';
$labels['account_default_folder'] = 'Dossier par défaut';
$labels['pop3fetcher_current_version'] = 'VERSION ACTUELLE: ';
$labels['pop3fetcher_latest_version'] = 'La dernière version est: ';
$labels['pop3fetcher_updated'] = 'Pop3fetcher est à jour';
$labels['pop3fetcher_outdated'] = "Il y a une mise à jour pour Pop3fetcher.<br />Téléchargez là depuis ";
$labels['account_import_old_messages'] = 'Importer les anciens messages';


/* FROM NOW ON: CHECK */
$labels['pluginname'] = 'Comptes IMAP Distants';
$labels['plugindescription'] = "Permet a un utilisateur d'accéder aux messages stockés dans des dossiers distants comme si ils étaient présents en local.";
$labels['account_dn'] = 'Nom du compte';
$labels['account_id'] = 'Login ID';
$labels['account_pw'] = 'Mot de passe';
$labels['account_pw_conf'] = 'Confirmer le mot de passe';
$labels['account_provider'] = 'Fournisseur';
$labels['add'] = 'Ajouter';
$labels['back'] = 'Annuler';
$labels['submit'] = 'Envoyer';
$labels['archivefolder'] = 'Archive';
$labels['remotefolders'] = 'Dossiers Spéciaux';
$labels['description'] = 'Gérer les comptes IMAP additionnels.';
$labels['dnempty'] = 'Entrez un nom pour ce compte';
$labels['userempty'] = "Entrez un ID d'identification pour ce compte";
$labels['passwordempty'] = 'Entrez un mot de passe';
$labels['passwordnotmatch'] = 'Le mot de passe ne correspond pas';
$labels['hostempty'] = "Entrez l'url hôte (p.e. ssl://imap.gmail.com:993)";
$labels['accountexists'] = 'Cecompte existe déja. Vous avez été redirigé en mode édition.';
$labels['connectionfailed'] = "Impossible d'établir la connexion à l'hôte distant.";

?>