<?php

$labels = array();
$labels['other_accounts'] = 'Andre kontoer';
$labels['editaccount'] = 'Rediger konto';
$labels['addaccount'] = 'Legg til POP3-konto';
$labels['account_email'] = 'E-post';
$labels['account_username'] = 'Brukernavn';
$labels['account_password'] = 'Passord';
$labels['account_serveraddress'] = 'Serveradresse';
$labels['account_serverport'] = 'Serverport';
$labels['account_usessl'] = 'Bruk SSL';
$labels['account_leaveacopy'] = 'La det være en kopi av meldinger på serveren';
$labels['account_unableconnect'] = "Kunne ikke koble til adressen";
$labels['account_provider'] = 'Leverandør';
$labels['test_connection_on_save'] = 'Test forbindelsen ved lagring';
$labels['account_default_folder'] = 'Standardmappe';
$labels['pop3fetcher_current_version'] = 'GJELDENDE VERSJON: ';
$labels['pop3fetcher_latest_version'] = 'Siste versjon er: ';
$labels['pop3fetcher_updated'] = 'Pop3fetcher er oppdatert til den nyeste versjonen';
$labels['pop3fetcher_outdated'] = "Det finnes en oppdatering for Pop3fetcher.<br />Last den ned fra ";
$labels['account_import_old_messages'] = 'Importer gamle meldinger';


$labels['pluginname'] = 'Eksterne IMAP-kontoer';
$labels['plugindescription'] = 'Gir en bruker tilgang til meldinger lagret i en ekstern mappe, akkurat som om det var en lokal mappe.';
$labels['account_dn'] = 'Kontonavn';
$labels['account_id'] = 'Påloggings-ID';
$labels['account_pw'] = 'Passord';
$labels['account_pw_conf'] = 'Bekreft passord';
$labels['account_provider'] = 'Leverandør';
$labels['add'] = 'Legg til';
$labels['back'] = 'Avbryt';
$labels['submit'] = 'Send';
$labels['archivefolder'] = 'Arkiver';
$labels['remotefolders'] = 'Spesielle mapper';
$labels['description'] = 'Behandle ekstra IMAP-kontoer.';
$labels['dnempty'] = 'Angi et navn for denne kontoen';
$labels['userempty'] = 'Angi påloggings-ID';
$labels['passwordempty'] = 'Angi passord';
$labels['passwordnotmatch'] = 'Passordet stemmer ikke';
$labels['hostempty'] = 'Angi URL-adresse til vert (f.eks. ssl://imap.gmail.com:993)';
$labels['accountexists'] = 'Denne kontoen finnes allerede. Du har blitt videresendt til redigeringsmodus.';
$labels['connectionfailed'] = 'Kunne ikke opprette tilkobling til ekstern vert.';
?>
