<?php

/*
+-----------------------------------------------------------------------+
| ./plugins/pop3fetcher/localization/nl_NL.inc                          | 
| Language file of roundcube-pop3fetcher plugin							| 
| Copyright (C) 2010-2013, Paolo 'morepaolo' Moretti					|	
| Licensed under the GNU GPL											|
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Paolo Moretti <morepaolo@gmail.com>            	            |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['other_accounts'] = 'Andere Accounts';
$labels['editaccount'] = 'Edit Account';
$labels['addaccount'] = 'Toevoegen Account';
$labels['account_email'] = 'Email';
$labels['account_username'] = 'Username';
$labels['account_password'] = 'Paswoord';
$labels['account_serveraddress'] = 'Server Address';
$labels['account_serverport'] = 'Server Port';
$labels['account_usessl'] = 'Gebruik SSL';
$labels['account_leaveacopy'] = 'Laat een copy van de mail op de server';
$labels['account_unableconnect'] = "Unable to connect to address";
$labels['account_provider'] = 'Provider';
$labels['test_connection_on_save'] = 'Test connection bij opslaan';
$labels['account_default_folder'] = 'Default Folder';
$labels['pop3fetcher_current_version'] = 'HUIDIGE VERSIE: ';
$labels['pop3fetcher_latest_version'] = 'Laatste versie is: ';
$labels['pop3fetcher_updated'] = 'Pop3fetcher is geupdated naar de laatste versie';
$labels['pop3fetcher_outdated'] = "Er is een update available voor Pop3fetcher.<br />Download het van ";
$labels['account_import_old_messages'] = 'Import old messages';

/* FROM NOW ON: CHECK */
$labels['remoteaccounts'] = 'Remote IMAP Accounts';
$labels['pluginname'] = 'Remote IMAP Accounts';
$labels['plugindescription'] = 'Allows a user to access messages stored in any remote folder as if it were a local folder.';
$labels['account_dn'] = 'Account Naam';
$labels['account_id'] = 'Login ID';
$labels['account_pw'] = 'Paswoord';
$labels['account_pw_conf'] = 'Bevestig Paswoord';
$labels['account_provider'] = 'Provider';
$labels['add'] = 'Toevoegen';
$labels['back'] = 'Afbreken';
$labels['submit'] = 'Submit';
$labels['archivefolder'] = 'Archive';
$labels['remotefolders'] = 'Speciale Folders';
$labels['description'] = 'Manage additional IMAP Accounts.';
$labels['dnempty'] = 'Enter een naam voor deze account';
$labels['userempty'] = 'Enter account login ID';
$labels['passwordempty'] = 'Enter paswoord';
$labels['passwordnotmatch'] = 'Paswoord komt niet overeen';
$labels['hostempty'] = 'Enter host url (v.b. ssl://imap.gmail.com:993)';
$labels['accountexists'] = 'Dit account bestaat al. Je wordt doorgestuurd naar de edit mode.';
$labels['connectionfailed'] = 'Faalt connectie met remote host.';

?>