<?php

/*
+-----------------------------------------------------------------------+
| ./plugins/pop3fetcher/localization/en_GB.inc                          | 
| Language file of roundcube-pop3fetcher plugin							| 
| Copyright (C) 2010-2013, Paolo 'morepaolo' Moretti					|	
| Licensed under the GNU GPL											|
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Łukasz Nowak <theqkash@theqkash.pl>            	            |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['other_accounts'] = 'Inne konta';
$labels['editaccount'] = 'Edytuj konto';
$labels['addaccount'] = 'Dodaj konto';
$labels['account_email'] = 'Email';
$labels['account_username'] = 'Nazwa użytkownika';
$labels['account_password'] = 'Hasło';
$labels['account_serveraddress'] = 'Adres serwera';
$labels['account_serverport'] = 'Port serwera';
$labels['account_usessl'] = 'Użyj SSL';
$labels['account_leaveacopy'] = 'Pozostaw kopię wiadomości na serwerze';
$labels['account_unableconnect'] = "Nie można połączyć się z adresem";
$labels['account_provider'] = 'Dostawca';
$labels['test_connection_on_save'] = 'Testuj połączenie przy zapisie';
$labels['account_default_folder'] = 'Domyślny katalog';
$labels['pop3fetcher_current_version'] = 'OBECNA WERSJA: ';
$labels['pop3fetcher_latest_version'] = 'Najnowszą dostępną jest: ';
$labels['pop3fetcher_updated'] = 'Pop3fetcher jest w najnowszej dostępnej wersji';
$labels['pop3fetcher_outdated'] = "Jest dostępna aktualizacja dla rozszerzenia pop3fetcher.<br />Pobierz ją z ";
$labels['account_import_old_messages'] = 'Importuj stare wiadomości';

/* FROM NOW ON: CHECK */
$labels['remoteaccounts'] = 'Zdalne konta IMAP';
$labels['pluginname'] = 'Zdalne konta IMAP';
$labels['plugindescription'] = 'Umożliwia użytkownikowi dostęp do wiadomości ulokowanych w folderze zdalnym tak jakby był folderem lokalnym.';
$labels['account_dn'] = 'Nazwa konta';
$labels['account_id'] = 'Login';
$labels['account_pw'] = 'Hasło';
$labels['account_pw_conf'] = 'Potwierdź hasło';
$labels['account_provider'] = 'Dostawca';
$labels['add'] = 'Dodaj';
$labels['back'] = 'Anuluj';
$labels['submit'] = 'Wyślij';
$labels['archivefolder'] = 'Archiwum';
$labels['remotefolders'] = 'Specialne foldery';
$labels['description'] = 'Zarządzaj dodatkowymi kontami IMAP.';
$labels['dnempty'] = 'Podaj nazwę dla tego konta';
$labels['userempty'] = 'Podaj login';
$labels['passwordempty'] = 'Podaj hasło';
$labels['passwordnotmatch'] = 'Hasła nie zgadzają się';
$labels['hostempty'] = 'Podaj URL hosta (np. ssl://imap.gmail.com:993)';
$labels['accountexists'] = 'To konto było już dodane. Nastąpiło przekierowanie do edycji konta.';
$labels['connectionfailed'] = 'Nie mozna nawiązać połączenia z hostem zdalnym.';

?>
