<?php

$labels = array();
$labels['other_accounts'] = 'Outras Contas';
$labels['editaccount'] = 'Editar Conta';
$labels['addaccount'] = 'Adicionar Conta POP3';
$labels['account_email'] = 'E-mail';
$labels['account_username'] = 'Nome de Usuário';
$labels['account_password'] = 'Senha';
$labels['account_serveraddress'] = 'Endereço do Servidor';
$labels['account_serverport'] = 'Porta do Servidor';
$labels['account_usessl'] = 'Usar SSL';
$labels['account_leaveacopy'] = 'Deixar uma cópia da mensagem no servidor';
$labels['account_unableconnect'] = "Não é possível se conectar ao endereço";
$labels['account_provider'] = 'Provedor';
$labels['test_connection_on_save'] = 'Testar conexão ao salvar';
$labels['account_default_folder'] = 'Pasta Padrão';
$labels['pop3fetcher_current_version'] = 'VERSÃO ATUAL:';
$labels['pop3fetcher_latest_version'] = 'A última versão é:';
$labels['pop3fetcher_updated'] = 'Pop3fetcher está atualizado para a última versão';
$labels['pop3fetcher_outdated'] = "Existe uma atualização disponível para Pop3fetcher.<br />Baixe de ";
$labels['account_import_old_messages'] = 'Importar mensagens antigas';


$labels['pluginname'] = 'Contas de IMAP Remotas';
$labels['plugindescription'] = 'Permite que um usuário acesse mensagens armazenadas em qualquer pasta remota como se fosse uma pasta local.';
$labels['account_dn'] = 'Nome da Conta';
$labels['account_id'] = 'Identificação de Entrada';
$labels['account_pw'] = 'Senha';
$labels['account_pw_conf'] = 'Confirme a Senha';
$labels['account_provider'] = 'Provedor';
$labels['add'] = 'Adicionar';
$labels['back'] = 'Abortar';
$labels['submit'] = 'Enviar';
$labels['archivefolder'] = 'Arquivar';
$labels['remotefolders'] = 'Pastas Especiais';
$labels['description'] = 'Gerenciar Contas Adicionais de IMAP.';
$labels['dnempty'] = 'Digite um nome para esta conta';
$labels['userempty'] = 'Digite a identificação de login da conta';
$labels['passwordempty'] = 'Digite a senha';
$labels['passwordnotmatch'] = 'Senha incorreta';
$labels['hostempty'] = 'Digite a url do servidor (f.e. ssl://imap.gmail.com:993)';
$labels['accountexists'] = 'Esta conta já existe. Você foi redirecionado ao modo editar.';
$labels['connectionfailed'] = 'Falha ao estabelecer conexão com o servidor remoto.';
?>
