<?php

$labels = array();
$labels['other_accounts'] = 'Andra konton';
$labels['editaccount'] = 'Redigera konto';
$labels['addaccount'] = 'Lägg till POP3-konto';
$labels['account_email'] = 'E-post';
$labels['account_username'] = 'Användarnamn';
$labels['account_password'] = 'Lösenord';
$labels['account_serveraddress'] = 'Serveradress';
$labels['account_serverport'] = 'Serverport';
$labels['account_usessl'] = 'Använd SSL';
$labels['account_leaveacopy'] = 'Lämna en kopia av meddelandet på servern';
$labels['account_unableconnect'] = 'Kan inte ansluta till adressen';
$labels['account_provider'] = 'Leverantör';
$labels['test_connection_on_save'] = 'Testanslutning på spara';
$labels['account_default_folder'] = 'Standardmapp';
$labels['pop3fetcher_current_version'] = 'NUVARANDE VERSION: ';
$labels['pop3fetcher_latest_version'] = 'Senaste version är: ';
$labels['pop3fetcher_updated'] = 'Pop3fetcher är uppdaterad till senaste version';
$labels['pop3fetcher_outdated'] = "Det finns en uppdatering tillgänglig för Pop3fetcher.<br />Ladda ner den från";
$labels['account_import_old_messages'] = 'Importera gamla meddelanden';


$labels['pluginname'] = 'Externa IMAP-konton';
$labels['plugindescription'] = 'Låter användaren få tillgång till meddelanden som sparats i valfri extern mapp som om den var en lokal mapp.';
$labels['account_dn'] = 'Kontonamn';
$labels['account_id'] = 'Inloggnings-ID';
$labels['account_pw'] = 'Lösenord';
$labels['account_pw_conf'] = 'Bekräfta lösenord';
$labels['account_provider'] = 'Leverantör';
$labels['add'] = 'Lägg till';
$labels['back'] = 'Avbryt';
$labels['submit'] = 'Skicka in';
$labels['archivefolder'] = 'Arkivera';
$labels['remotefolders'] = 'Specialmappar';
$labels['description'] = 'Hantera flera IMAP-konton.';
$labels['dnempty'] = 'Ange ett namn för detta konto';
$labels['userempty'] = 'Ange inloggnings-ID för konto';
$labels['passwordempty'] = 'Ange lösenord';
$labels['passwordnotmatch'] = 'Lösenord matchar inte';
$labels['hostempty'] = 'Ange serverns url (f.e. ssl://imap.gmail.com:993)';
$labels['accountexists'] = 'Det kontot finns redan. Du har omdirigerats till redigeringsläge.';
$labels['connectionfailed'] = 'Misslyckades med att ansluta till extern server.';
?>
